export type LaundryAccessCopy = {
  ready: string; guestInside: string; guestPermission: string; dnd: string; unavailable: string;
  full: string; textile: string; towel: string; daily: string; noService: string;
  housekeeper: string; unassigned: string; service: string; accessConfirm: string;
  accessReminder: string; cannotOpen: string; loadingInfo: string; readyCount: string;
  permissionMissing: string; serviceDue: string; roomUpdated: string;
};

const en: LaundryAccessCopy = {
  ready: 'Ready to collect', guestInside: 'Guest still inside / not released', guestPermission: 'Ask guest first',
  dnd: 'DND – do not enter', unavailable: 'Unavailable', full: 'Full room clean',
  textile: 'Complete textile change', towel: 'Towel change only', daily: 'Daily service (confirm type)',
  noService: 'No cleaning scheduled', housekeeper: 'Housekeeper', unassigned: 'Not assigned',
  service: 'Service', accessConfirm: 'Guest has granted permission to enter and collect linen',
  accessReminder: 'Stayover: confirm guest permission before entering; room status alone is not consent.',
  cannotOpen: 'This checkout is not released. Wait until reception marks it ready to clean; do not enter.',
  loadingInfo: 'Checking room access…', readyCount: 'checkout rooms ready to collect',
  permissionMissing: 'Confirm the guest has granted access before collecting linen.', serviceDue: 'Service-due stayovers',
  roomUpdated: 'Room access changed. The latest room information has been loaded.',
};

const translations: Record<string, LaundryAccessCopy> = {
  en,
  hu: { ready: 'Textíliagyűjtésre kész', guestInside: 'A vendég még bent van / a szoba nincs felszabadítva', guestPermission: 'Előbb kérj engedélyt', dnd: 'Ne zavarjanak – tilos belépni', unavailable: 'Nem elérhető', full: 'Teljes szobatakarítás', textile: 'Teljes textilcsere', towel: 'Csak törölközőcsere', daily: 'Napi szerviz (típus ellenőrzendő)', noService: 'Nincs ütemezett takarítás', housekeeper: 'Szobaasszony', unassigned: 'Nincs kiosztva', service: 'Szerviz', accessConfirm: 'A vendég engedélyezte a belépést és a textíliagyűjtést', accessReminder: 'Lakott szoba: belépés előtt kérj vendégengedélyt. A szobastátusz nem jelent beleegyezést.', cannotOpen: 'A kijelentkező szoba még nincs felszabadítva. Várd meg, amíg a recepció takarításra késznek jelöli. Ne lépj be.', loadingInfo: 'Belépési feltételek ellenőrzése…', readyCount: 'textíliagyűjtésre kész kijelentkező szoba', permissionMissing: 'Gyűjtés előtt erősítsd meg a vendég engedélyét.', serviceDue: 'Esedékes szervizű lakott szobák', roomUpdated: 'A szoba hozzáférése megváltozott. A legfrissebb adatok betöltve.' },
  es: { ready: 'Lista para recoger', guestInside: 'Huésped dentro / habitación no liberada', guestPermission: 'Pide permiso al huésped', dnd: 'No molestar – no entrar', unavailable: 'No disponible', full: 'Limpieza completa', textile: 'Cambio completo de textiles', towel: 'Solo cambio de toallas', daily: 'Servicio diario (confirmar tipo)', noService: 'Sin limpieza programada', housekeeper: 'Personal de limpieza', unassigned: 'Sin asignar', service: 'Servicio', accessConfirm: 'El huésped autorizó entrar y recoger la ropa', accessReminder: 'Habitación ocupada: solicita permiso antes de entrar. El estado no equivale a consentimiento.', cannotOpen: 'Esta salida aún no está liberada. Espera a que recepción indique lista para limpiar. No entres.', loadingInfo: 'Comprobando acceso…', readyCount: 'salidas listas para recoger', permissionMissing: 'Confirma el permiso del huésped antes de recoger.', serviceDue: 'Habitaciones ocupadas con servicio pendiente', roomUpdated: 'Cambió el acceso a la habitación. Datos actualizados.' },
  vi: { ready: 'Sẵn sàng thu đồ vải', guestInside: 'Khách còn trong phòng / chưa bàn giao', guestPermission: 'Xin phép khách trước', dnd: 'Không làm phiền – không vào', unavailable: 'Không khả dụng', full: 'Dọn phòng toàn bộ', textile: 'Thay toàn bộ đồ vải', towel: 'Chỉ thay khăn', daily: 'Dịch vụ hằng ngày (xác nhận loại)', noService: 'Không có lịch dọn phòng', housekeeper: 'Nhân viên buồng phòng', unassigned: 'Chưa phân công', service: 'Dịch vụ', accessConfirm: 'Khách đã cho phép vào phòng để thu đồ vải', accessReminder: 'Phòng đang có khách: phải xin phép trước khi vào. Trạng thái phòng không phải sự đồng ý.', cannotOpen: 'Phòng trả chưa được bàn giao. Chờ lễ tân đánh dấu sẵn sàng dọn. Không được vào.', loadingInfo: 'Đang kiểm tra quyền vào phòng…', readyCount: 'phòng trả sẵn sàng thu đồ vải', permissionMissing: 'Xác nhận khách cho phép trước khi thu.', serviceDue: 'Phòng đang ở đến lịch phục vụ', roomUpdated: 'Quyền vào phòng đã thay đổi. Đã tải dữ liệu mới.' },
  mn: { ready: 'Цагаан хэрэглэл авахад бэлэн', guestInside: 'Зочин дотор байна / өрөө чөлөөлөгдөөгүй', guestPermission: 'Эхлээд зочноос зөвшөөрөл ав', dnd: 'Бүү саад бол – орж болохгүй', unavailable: 'Боломжгүй', full: 'Өрөө бүрэн цэвэрлэх', textile: 'Бүх цагаан хэрэглэл солих', towel: 'Зөвхөн алчуур солих', daily: 'Өдрийн үйлчилгээ (төрлийг шалга)', noService: 'Цэвэрлэгээ товлоогүй', housekeeper: 'Өрөөний үйлчлэгч', unassigned: 'Хуваарилаагүй', service: 'Үйлчилгээ', accessConfirm: 'Зочин орж цагаан хэрэглэл авахыг зөвшөөрсөн', accessReminder: 'Зочинтой өрөө: орохоос өмнө зөвшөөрөл ав. Өрөөний төлөв зөвшөөрөл биш.', cannotOpen: 'Гарах өрөө чөлөөлөгдөөгүй. Ресепшн цэвэрлэхэд бэлэн гэж тэмдэглэх хүртэл хүлээ. Бүү ор.', loadingInfo: 'Өрөөнд нэвтрэх эрхийг шалгаж байна…', readyCount: 'цагаан хэрэглэл авахад бэлэн гарах өрөө', permissionMissing: 'Цуглуулахын өмнө зочны зөвшөөрлийг баталгаажуул.', serviceDue: 'Үйлчилгээ хийх хугацаа болсон өрөөнүүд', roomUpdated: 'Өрөөнд нэвтрэх төлөв өөрчлөгдсөн. Мэдээлэл шинэчлэгдлээ.' },
  az: { ready: 'Çamaşır yığmağa hazır', guestInside: 'Qonaq hələ içəridədir / otaq təhvil verilməyib', guestPermission: 'Əvvəlcə qonaqdan icazə alın', dnd: 'Narahat etməyin – daxil olmayın', unavailable: 'Əlçatan deyil', full: 'Otağın tam təmizliyi', textile: 'Bütün tekstilin dəyişdirilməsi', towel: 'Yalnız dəsmal dəyişikliyi', daily: 'Gündəlik xidmət (növünü yoxlayın)', noService: 'Təmizlik planlaşdırılmayıb', housekeeper: 'Otaq təmizləyicisi', unassigned: 'Təyin edilməyib', service: 'Xidmət', accessConfirm: 'Qonaq daxil olmağa və tekstili yığmağa icazə verib', accessReminder: 'Qonaqlı otaq: daxil olmadan əvvəl icazə alın. Otaq statusu razılıq demək deyil.', cannotOpen: 'Çıxış otağı hələ təhvil verilməyib. Resepsiyanın təmizliyə hazır işarəsini gözləyin. Daxil olmayın.', loadingInfo: 'Otağa giriş yoxlanılır…', readyCount: 'tekstil yığmağa hazır çıxış otağı', permissionMissing: 'Yığmadan əvvəl qonağın icazəsini təsdiqləyin.', serviceDue: 'Xidməti vaxtı çatmış qonaqlı otaqlar', roomUpdated: 'Otağa giriş statusu dəyişib. Son məlumatlar yükləndi.' },
  tl: { ready: 'Handa nang kolektahin', guestInside: 'May bisita pa / hindi pa na-release', guestPermission: 'Humingi muna ng pahintulot', dnd: 'Huwag istorbohin – huwag pumasok', unavailable: 'Hindi available', full: 'Buong paglilinis ng kuwarto', textile: 'Kumpletong palit ng linen', towel: 'Palit-tuwalya lamang', daily: 'Arawang serbisyo (kumpirmahin)', noService: 'Walang nakatakdang paglilinis', housekeeper: 'Housekeeper', unassigned: 'Walang naka-assign', service: 'Serbisyo', accessConfirm: 'Pinayagan ng bisita ang pagpasok at pagkuha ng linen', accessReminder: 'May bisita: humingi muna ng pahintulot. Hindi pahintulot ang status ng kuwarto.', cannotOpen: 'Hindi pa na-release ang checkout room. Hintaying markahan ng reception na ready to clean. Huwag pumasok.', loadingInfo: 'Sinusuri ang pahintulot…', readyCount: 'checkout room na handa nang kolektahin', permissionMissing: 'Kumpirmahin ang pahintulot ng bisita bago mangolekta.', serviceDue: 'Stayover na dapat serbisyuhan', roomUpdated: 'Nagbago ang pahintulot sa kuwarto. Na-load ang bagong impormasyon.' },
  uk: { ready: 'Готово до збору білизни', guestInside: 'Гість ще в номері / номер не звільнено', guestPermission: 'Спочатку запитайте дозволу гостя', dnd: 'Не турбувати – не входити', unavailable: 'Недоступно', full: 'Повне прибирання номера', textile: 'Повна заміна текстилю', towel: 'Лише заміна рушників', daily: 'Щоденне обслуговування (уточніть тип)', noService: 'Прибирання не заплановано', housekeeper: 'Покоївка', unassigned: 'Не призначено', service: 'Обслуговування', accessConfirm: 'Гість дозволив увійти та забрати білизну', accessReminder: 'Зайнятий номер: перед входом отримайте дозвіл гостя. Статус номера не є згодою.', cannotOpen: 'Номер після виїзду ще не звільнено. Дочекайтеся позначки від рецепції про готовність до прибирання. Не входьте.', loadingInfo: 'Перевірка доступу до номера…', readyCount: 'номерів після виїзду готові до збору', permissionMissing: 'Підтвердьте дозвіл гостя перед збором білизни.', serviceDue: 'Зайняті номери з плановим обслуговуванням', roomUpdated: 'Доступ до номера змінився. Дані оновлено.' },
  ru: { ready: 'Готов к сбору белья', guestInside: 'Гость ещё внутри / номер не освобождён', guestPermission: 'Сначала спросите разрешение гостя', dnd: 'Не беспокоить – не входить', unavailable: 'Недоступен', full: 'Полная уборка номера', textile: 'Полная смена белья', towel: 'Только замена полотенец', daily: 'Ежедневное обслуживание (уточните тип)', noService: 'Уборка не запланирована', housekeeper: 'Горничная', unassigned: 'Не назначено', service: 'Обслуживание', accessConfirm: 'Гость разрешил войти и забрать бельё', accessReminder: 'Занятый номер: получите разрешение перед входом. Статус номера не означает согласие.', cannotOpen: 'Номер после выезда ещё не освобождён. Дождитесь отметки рецепции о готовности к уборке. Не входите.', loadingInfo: 'Проверка доступа к номеру…', readyCount: 'номеров после выезда готовы к сбору', permissionMissing: 'Подтвердите разрешение гостя перед сбором белья.', serviceDue: 'Занятые номера с назначенным обслуживанием', roomUpdated: 'Доступ к номеру изменился. Данные обновлены.' },
};

export const laundryAccessCopy = (language: string): LaundryAccessCopy => translations[language] || en;
