// Admin — PMS Overview & Configuration module
import type { TrainingCurriculum } from '../types';

export const adminPmsOverviewCurriculum: TrainingCurriculum = {
  slug: 'v2_admin_pms_overview',
  name: {
    en: 'PMS Overview & Configuration (Admin)',
    hu: 'PMS áttekintés és konfiguráció (Admin)',
    es: 'Descripción y configuración PMS (Admin)',
    vi: 'Tổng quan & Cấu hình PMS (Admin)',
    mn: 'PMS тохиргоо ба удирдлага (Админ)',
  },
  description: {
    en: 'Configure Previo per hotel, toggle the legacy Upload tab, and understand the Yesterday/Today overview.',
    hu: 'Previo hotelenkénti beállítás, régi PMS Upload elrejtése, és a Tegnap/Ma áttekintés.',
    es: 'Configura Previo por hotel, oculta la carga heredada y usa la vista Ayer/Hoy.',
    vi: 'Cấu hình Previo cho từng khách sạn, ẩn tab tải cũ, và dùng chế độ Hôm qua/Hôm nay.',
    mn: 'Зочид буудал бүрд Previo тохируулах, хуучин Upload табыг нуух, Өчигдөр/Өнөөдрийг ойлгох.',
  },
  roles: ['admin'],
  category: 'feature_promo',
  priority: 15,
  moduleKey: 'admin',
  estMinutes: 3,
  steps: [
    {
      key: 'select_hotel',
      title: {
        en: 'Admin → PMS Config',
        hu: 'Admin → PMS Konfiguráció',
        es: 'Admin → Config. PMS',
        vi: 'Admin → PMS Config',
        mn: 'Админ → PMS тохиргоо',
      },
      body: {
        en: 'Open the Admin section and pick "PMS Config". On mobile the tabs bar now scrolls horizontally, so every tab (Organizations, Hotels, PMS Config, Translations, Breakfast, Training, System) is reachable.',
        hu: 'Nyisd meg az Admin szakaszt és válaszd a "PMS Config" fület. Mobilon a fülek most görgethetők.',
        es: 'Abre Admin y elige "PMS Config". En móvil los tabs ahora se pueden desplazar.',
        vi: 'Vào Admin và chọn "PMS Config". Trên di động thanh tab đã có thể cuộn ngang.',
        mn: 'Админ хэсэг рүү орж "PMS Config"-г сонго. Гар утсан дээр таб хэвтээ гүйдэг.',
      },
      route: '/:org',
      tab: 'admin',
      optional: true,
    },
    {
      key: 'hide_upload_toggle',
      title: {
        en: 'Hide the legacy PMS Upload tab',
        hu: 'A régi PMS Upload fül elrejtése',
        es: 'Ocultar la pestaña heredada de carga PMS',
        vi: 'Ẩn tab tải PMS cũ',
        mn: 'Хуучин PMS Upload табыг нуух',
      },
      body: {
        en: 'Inside the Previo Configuration card, turn on "Hide legacy PMS Upload tab". Managers of this hotel will only see Team View → PMS Refresh. Keep it OFF only when you need the XLSX upload as a fallback.',
        hu: 'A Previo kártyán kapcsold be a "Hide legacy PMS Upload tab" kapcsolót — a menedzserek csak a Team View-t látják.',
        es: 'En la tarjeta Previo, activa "Ocultar carga PMS" — los mánagers solo verán Team View → PMS Refresh.',
        vi: 'Trong thẻ Previo, bật "Hide legacy PMS Upload tab" — quản lý chỉ thấy Team View → PMS Refresh.',
        mn: 'Previo картанд "Hide legacy PMS Upload tab"-г асаа. Менежерүүд зөвхөн Team View-г харна.',
      },
      route: '/:org',
      tab: 'admin',
      selector: '#hide-pms-upload-page',
      optional: true,
    },
    {
      key: 'test_connection',
      title: {
        en: 'Test the connection',
        hu: 'Kapcsolat tesztelése',
        es: 'Probar la conexión',
        vi: 'Kiểm tra kết nối',
        mn: 'Холболтыг шалгах',
      },
      body: {
        en: 'After saving, hit "Test Connection". A green check means Previo credentials work; a red X shows the exact error to send back to Previo support.',
        hu: 'Mentés után kattints a "Test Connection" gombra. Zöld pipa = működik, piros X = hiba.',
        es: 'Tras guardar, pulsa "Test Connection". Verde = OK, rojo = error.',
        vi: 'Sau khi lưu, bấm "Test Connection". Xanh = OK, đỏ = lỗi.',
        mn: 'Хадгалсны дараа "Test Connection" дар. Ногоон = амжилттай, улаан = алдаа.',
      },
      route: '/:org',
      tab: 'admin',
      optional: true,
    },
    {
      key: 'yesterday_today_admin',
      title: {
        en: 'Yesterday vs Today view (admin-only)',
        hu: 'Tegnap vs Ma nézet (csak admin)',
        es: 'Vista Ayer vs Hoy (solo admin)',
        vi: 'Chế độ Hôm qua vs Hôm nay (chỉ admin)',
        mn: 'Өчигдөр vs Өнөөдөр харагдац (зөвхөн админ)',
      },
      body: {
        en: 'Admins see the room overview split into Yesterday (read-only) and Today. Managers see only Today. This keeps floor staff focused while giving you the full audit trail.',
        hu: 'Az adminok kétoszlopos nézetet látnak; a menedzserek csak a mait. Ez tisztán tartja a csapat nézetét.',
        es: 'Los admins ven Ayer + Hoy; los mánagers solo Hoy — vista de equipo más clara.',
        vi: 'Admin xem Hôm qua + Hôm nay; quản lý chỉ Hôm nay — giao diện gọn gàng hơn.',
        mn: 'Админ хоёр багана, менежер зөвхөн өнөөдрийг харна — багийн харагдац цэвэрхэн.',
      },
      route: '/:org',
      tab: 'housekeeping',
      selector: '[data-training="team-view"]',
      optional: true,
    },
    {
      key: 'push_to_previo',
      title: {
        en: 'Approvals push clean status to Previo',
        hu: 'A jóváhagyások szinkronizálják a szoba állapotát Previo-ba',
        es: 'Al aprobar se envía el estado "limpio" a Previo',
        vi: 'Duyệt phòng sẽ gửi trạng thái sạch về Previo',
        mn: 'Зөвшөөрөл нь Previo руу "цэвэр" төлөвийг илгээнэ',
      },
      body: {
        en: 'When you approve a cleaned room in Pending Approvals, the system marks the matching Previo room as clean automatically via the outbound queue. No manual step needed.',
        hu: 'A jóváhagyott szobák automatikusan Previo-ba is felkerülnek tisztaként.',
        es: 'Las habitaciones aprobadas se marcan "limpias" en Previo automáticamente.',
        vi: 'Các phòng đã duyệt tự động chuyển sang "sạch" trong Previo.',
        mn: 'Зөвшөөрөгдсөн өрөө Previo дээр автоматаар "цэвэр" болно.',
      },
      route: '/:org',
      tab: 'housekeeping',
      selector: '[data-training="pending-approvals"]',
      optional: true,
    },
  ],
};
