// Housekeeper "Your First Shift" curriculum.
// Mobile-first and hands-on: real actions are gated, while situational tools
// are explained without forcing staff to create false operational records.
import type { I18nText, TrainingCurriculum } from '../types';

const t6 = (
  en: string,
  hu: string,
  es: string,
  vi: string,
  mn: string,
  uk: string,
): I18nText => ({ en, hu, es, vi, mn, uk });

const START_SHIFT = t6('1 · Start your shift', '1 · Műszak kezdése', '1 · Empieza tu turno', '1 · Bắt đầu ca làm', '1 · Ээлжээ эхлүүлэх', '1 · Початок зміни');
const YOUR_ROOM = t6('2 · Start your room', '2 · Szoba indítása', '2 · Empieza tu habitación', '2 · Bắt đầu phòng', '2 · Өрөөгөө эхлүүлэх', '2 · Початок роботи в номері');
const IN_ROOM = t6('3 · Work inside the room', '3 · Munka a szobában', '3 · Trabajo dentro de la habitación', '3 · Làm việc trong phòng', '3 · Өрөөнд ажиллах', '3 · Робота в номері');
const FINISH = t6('4 · Finish safely', '4 · Biztonságos befejezés', '4 · Finaliza correctamente', '4 · Hoàn tất đúng cách', '4 · Зөв дуусгах', '4 · Правильне завершення');

const roomToolBase = {
  route: '/:org',
  tab: 'housekeeping',
  precondition: 'has_in_progress_cleaning' as const,
  optional: true,
};

export const housekeeperCurriculum: TrainingCurriculum = {
  slug: 'v2_housekeeper_first_day',
  name: t6('Your First Shift — Housekeeping', 'Az első műszakod — Housekeeping', 'Tu primer turno — Housekeeping', 'Ca làm đầu tiên — Buồng phòng', 'Анхны ээлж — Өрөө үйлчилгээ', 'Ваша перша зміна — Housekeeping'),
  description: t6(
    'A guided first shift using your real attendance, room and room tools. Learn what to use, when to use it and how to finish safely.',
    'Vezetett első műszak a valódi jelenléttel, szobával és szobai funkciókkal. Megtanulod, mit mikor használj és hogyan fejezd be biztonságosan.',
    'Un primer turno guiado con tu asistencia, habitación y herramientas reales. Aprende qué usar, cuándo usarlo y cómo terminar correctamente.',
    'Ca đầu tiên có hướng dẫn với chấm công, phòng và công cụ thật. Học dùng gì, khi nào dùng và cách kết thúc đúng.',
    'Бодит ирц, өрөө, хэрэгслүүд дээр тулгуурласан анхны ээлжийн заавар. Юуг хэзээ ашиглах, хэрхэн зөв дуусгахыг сурна.',
    'Покрокова перша зміна з реальною відміткою, номером та інструментами. Дізнайтеся, що й коли використовувати та як правильно завершити роботу.',
  ),
  roles: ['housekeeping'], category: 'core', priority: 10, moduleKey: 'housekeeping', estMinutes: 8, isFullWalkthrough: true,
  steps: [
    {
      key: 'welcome', phase: START_SHIFT,
      title: t6('Welcome — this is your daily working routine 👋', 'Üdvözlünk — ez a napi munkameneted 👋', 'Bienvenido — esta es tu rutina diaria 👋', 'Chào mừng — đây là quy trình làm việc hằng ngày 👋', 'Тавтай морил — энэ бол таны өдөр тутмын дараалал 👋', 'Ласкаво просимо — це ваш щоденний робочий порядок 👋'),
      body: t6('Hotel Care guides you in the same order you work: check in, start a room, use only the tools that apply, complete the room, then end the shift after your work is finished.', 'A Hotel Care a munkád sorrendjében vezet: bejelentkezés, szoba indítása, csak a szükséges funkciók használata, szoba lezárása, majd műszakzárás a munka befejezése után.', 'Hotel Care te guía en el mismo orden de trabajo: entrada, iniciar habitación, usar solo las herramientas necesarias, completar la habitación y cerrar el turno al terminar.', 'Hotel Care hướng dẫn theo đúng thứ tự làm việc: chấm công, bắt đầu phòng, chỉ dùng công cụ phù hợp, hoàn tất phòng rồi kết thúc ca khi công việc đã xong.', 'Hotel Care ажлын дарааллаар чиглүүлнэ: бүртгүүлэх, өрөө эхлүүлэх, зөвхөн шаардлагатай хэрэгслүүдийг ашиглах, өрөөг дуусгах, дараа нь ажлаа дуусгаад ээлжээ хаах.', 'Hotel Care веде у робочому порядку: відмітка, початок номера, використання лише потрібних інструментів, завершення номера і закриття зміни після виконання роботи.'),
      purpose: t6('A consistent routine prevents missed rooms, missing evidence and unfinished work.', 'Az egységes rutin megelőzi a kimaradt szobákat, hiányzó bizonyítékokat és befejezetlen munkát.', 'Una rutina constante evita habitaciones omitidas, pruebas faltantes y trabajo sin terminar.', 'Quy trình nhất quán giúp tránh bỏ sót phòng, thiếu bằng chứng và công việc chưa hoàn tất.', 'Тогтмол дараалал өрөө алгасах, нотолгоо дутуу, ажил дуусаагүй үлдэхээс сэргийлнэ.', 'Послідовний порядок запобігає пропущеним номерам, відсутнім доказам і незавершеній роботі.'),
      tip: t6('The guide follows your own user, current hotel and selected language. You can continue later from Training Center.', 'Az útmutató a saját felhasználódat, aktuális hoteledet és választott nyelvedet követi. Később a Tréningközpontból folytathatod.', 'La guía sigue tu usuario, hotel actual e idioma elegido. Puedes continuar luego desde el Centro de formación.', 'Hướng dẫn theo tài khoản, khách sạn hiện tại và ngôn ngữ bạn chọn. Có thể tiếp tục sau từ Trung tâm đào tạo.', 'Заавар таны хэрэглэгч, одоогийн зочид буудал, сонгосон хэлийг дагана. Дараа Сургалтын төвөөс үргэлжлүүлж болно.', 'Навчання враховує вашого користувача, поточний готель і вибрану мову. Продовжити можна пізніше з Центру навчання.'),
    },
    {
      key: 'signin', phase: START_SHIFT,
      title: t6('Check in on site to start your shift', 'Jelentkezz be a helyszínen a műszakhoz', 'Registra tu entrada en el hotel', 'Chấm công tại chỗ để bắt đầu ca', 'Ээлжээ эхлүүлэхийн тулд газар дээр нь бүртгүүл', 'Відмітьтеся на місці, щоб почати зміну'),
      body: t6('Swipe the highlighted check-in control. If your phone asks for location, allow it so Hotel Care can confirm that the shift started at the hotel. The guide continues automatically.', 'Húzd el a kiemelt bejelentkezés vezérlőt. Ha a telefon helyadatot kér, engedélyezd, hogy a Hotel Care igazolhassa a helyszíni műszakkezdést. Az útmutató automatikusan folytatódik.', 'Desliza el control resaltado. Si el teléfono pide ubicación, permítela para confirmar que el turno empezó en el hotel. La guía continúa automáticamente.', 'Vuốt nút chấm công được làm nổi bật. Nếu điện thoại hỏi vị trí, hãy cho phép để xác nhận ca bắt đầu tại khách sạn. Hướng dẫn sẽ tự tiếp tục.', 'Онцолсон бүртгүүлэх удирдлагыг гулсуулна уу. Утас байршил асуувал ээлж зочид буудал дээр эхэлснийг батлахын тулд зөвшөөрнө үү. Заавар автоматаар үргэлжилнэ.', 'Проведіть по підсвіченому елементу входу. Якщо телефон запитає геолокацію, дозвольте її для підтвердження початку зміни в готелі. Навчання продовжиться автоматично.'),
      purpose: t6('Attendance and room work must belong to the same active shift so your working time is accurate.', 'A jelenlétnek és a szobai munkának ugyanahhoz az aktív műszakhoz kell tartoznia, hogy a munkaidő pontos legyen.', 'La asistencia y el trabajo de habitaciones deben pertenecer al mismo turno para que las horas sean correctas.', 'Chấm công và công việc phòng phải thuộc cùng một ca để giờ làm chính xác.', 'Ирц ба өрөөний ажил нэг идэвхтэй ээлжид хамаарах ёстой бөгөөд ингэснээр ажлын цаг зөв байна.', 'Відвідуваність і робота з номерами мають належати одній активній зміні, щоб робочий час був точним.'),
      tip: t6('If location was blocked before, enable location permission and try again.', 'Ha korábban letiltottad a helyadatot, engedélyezd, majd próbáld újra.', 'Si antes bloqueaste la ubicación, actívala y vuelve a intentarlo.', 'Nếu đã chặn vị trí trước đó, hãy bật quyền vị trí rồi thử lại.', 'Байршлыг өмнө нь хориглосон бол зөвшөөрөөд дахин оролдоно уу.', 'Якщо геолокацію було заблоковано, увімкніть дозвіл і спробуйте знову.'),
      route: '/:org', tab: 'attendance', selector: '[data-training="check-in-button"]', waitFor: 'is_signed_in',
    },
    {
      key: 'breaks', phase: START_SHIFT,
      title: t6('Use Break when you actually stop working', 'A Szünet funkciót akkor használd, amikor ténylegesen szünetelsz', 'Usa Pausa cuando realmente dejes de trabajar', 'Dùng Nghỉ khi bạn thực sự ngừng làm việc', 'Үнэхээр ажлаа зогсоох үед Завсарлага ашиглана уу', 'Використовуйте Перерву, коли справді припиняєте роботу'),
      body: t6('Start a break here and end it when you return. Hotel Care pauses working time during the break and resumes it afterwards.', 'Itt indítsd el a szünetet, és visszatéréskor zárd le. A Hotel Care a szünet alatt megállítja, utána folytatja a munkaidőt.', 'Inicia aquí la pausa y termínala al volver. Hotel Care pausa el tiempo de trabajo durante la pausa y lo reanuda después.', 'Bắt đầu nghỉ tại đây và kết thúc khi quay lại. Hotel Care tạm dừng thời gian làm việc trong lúc nghỉ và tiếp tục sau đó.', 'Завсарлагыг энд эхлүүлж, буцаж ирэхдээ дуусгана. Hotel Care завсарлагын үед ажлын цагийг түр зогсоож, дараа нь үргэлжлүүлнэ.', 'Починайте перерву тут і завершуйте після повернення. Hotel Care призупиняє робочий час на перерві та відновлює його після неї.'),
      purpose: t6('Correct break tracking keeps attendance and performance data fair and accurate.', 'A helyes szünetkezelés pontos és igazságos jelenléti és teljesítményadatokat biztosít.', 'Registrar bien las pausas mantiene precisos y justos los datos de asistencia y rendimiento.', 'Theo dõi giờ nghỉ đúng giúp dữ liệu chấm công và hiệu suất công bằng, chính xác.', 'Завсарлагыг зөв бүртгэх нь ирц, гүйцэтгэлийн мэдээллийг шударга, зөв байлгана.', 'Правильний облік перерв зберігає дані відвідуваності та продуктивності точними й справедливими.'),
      route: '/:org', tab: 'attendance', selector: '[data-training="break-controls"]', precondition: 'is_signed_in', optional: true,
    },
    {
      key: 'my_tasks', phase: YOUR_ROOM,
      title: t6('Open My Tasks and start your assigned room', 'Nyisd meg a Saját feladatok oldalt, és indítsd el a kijelölt szobát', 'Abre Mis tareas e inicia tu habitación asignada', 'Mở Công việc của tôi và bắt đầu phòng được giao', 'Миний даалгавар хэсгийг нээгээд оноосон өрөөгөө эхлүүл', 'Відкрийте Мої завдання та почніть призначений номер'),
      body: t6('Your assigned rooms are listed here with status and priority. Use Start Cleaning on the room you are actually entering. The timer and room status will start automatically.', 'Itt látod a kijelölt szobákat állapottal és prioritással. Annál a szobánál válaszd a Takarítás indítása funkciót, amelybe ténylegesen belépsz. Az időmérő és a szobaállapot automatikusan elindul.', 'Aquí aparecen tus habitaciones con estado y prioridad. Usa Iniciar limpieza en la habitación a la que realmente entras. El temporizador y el estado comenzarán automáticamente.', 'Các phòng được giao hiển thị ở đây cùng trạng thái và ưu tiên. Chỉ bấm Bắt đầu dọn khi bạn thực sự vào phòng. Bộ đếm thời gian và trạng thái sẽ tự bắt đầu.', 'Оноосон өрөөнүүд төлөв, эрэмбийн хамт энд харагдана. Үнэхээр орж буй өрөөндөө Цэвэрлэгээ эхлүүлэхийг ашиглана. Цаг хэмжигч, төлөв автоматаар эхэлнэ.', 'Призначені номери показані тут зі статусом і пріоритетом. Натискайте Почати прибирання лише для номера, до якого реально заходите. Таймер і статус запустяться автоматично.'),
      purpose: t6('Starting the correct room tells the team what you are working on and measures the room time correctly.', 'A megfelelő szoba indítása megmutatja a csapatnak, min dolgozol, és pontosan méri a szobára fordított időt.', 'Iniciar la habitación correcta informa al equipo y mide correctamente el tiempo de trabajo.', 'Bắt đầu đúng phòng giúp đội biết bạn đang làm gì và đo thời gian phòng chính xác.', 'Зөв өрөөг эхлүүлэх нь багт таны юу хийж байгааг харуулж, хугацааг зөв хэмжинэ.', 'Початок правильного номера показує команді, над чим ви працюєте, і точно вимірює час.'),
      tip: t6('Read the room type, stay/checkout status and any priority before starting.', 'Indítás előtt nézd meg a szobatípust, stay/checkout állapotot és a prioritást.', 'Antes de empezar, revisa tipo de habitación, estancia/salida y prioridad.', 'Trước khi bắt đầu, kiểm tra loại phòng, khách ở tiếp/trả phòng và mức ưu tiên.', 'Эхлэхээс өмнө өрөөний төрөл, stay/checkout төлөв, эрэмбийг шалгана уу.', 'Перед початком перевірте тип номера, статус проживання/виїзду та пріоритет.'),
      route: '/:org', tab: 'my-tasks', selector: '[data-training="start-room-button"]', precondition: 'has_any_assignment_today', waitFor: 'has_in_progress_cleaning', optional: true,
    },
    {
      key: 'special_instructions', phase: YOUR_ROOM,
      title: t6('Read room instructions before cleaning', 'Takarítás előtt olvasd el a szoba utasításait', 'Lee las instrucciones antes de limpiar', 'Đọc hướng dẫn phòng trước khi dọn', 'Цэвэрлэхээс өмнө өрөөний зааврыг унш', 'Прочитайте інструкції до номера перед прибиранням'),
      body: t6('Check any guest request, manager instruction or special note before you continue. These instructions can change how the room must be handled.', 'Folytatás előtt ellenőrizd a vendégkérést, vezetői utasítást vagy külön megjegyzést. Ezek módosíthatják a szoba kezelését.', 'Revisa solicitudes del huésped, instrucciones del responsable o notas especiales antes de continuar. Pueden cambiar cómo debes atender la habitación.', 'Kiểm tra yêu cầu của khách, hướng dẫn của quản lý hoặc ghi chú đặc biệt trước khi tiếp tục. Chúng có thể thay đổi cách xử lý phòng.', 'Үргэлжлүүлэхээс өмнө зочны хүсэлт, менежерийн заавар, тусгай тэмдэглэлийг шалгана уу. Эдгээр нь өрөөг хэрхэн ажиллахыг өөрчилж болно.', 'Перед продовженням перевірте запити гостя, інструкції менеджера та спеціальні примітки. Вони можуть змінити порядок роботи з номером.'),
      purpose: t6('Important room-specific information must be seen before work is completed.', 'A szobára vonatkozó fontos információt a munka befejezése előtt látni kell.', 'La información importante de la habitación debe verse antes de terminar el trabajo.', 'Thông tin quan trọng riêng của phòng phải được đọc trước khi hoàn tất.', 'Өрөөний чухал тусгай мэдээллийг ажил дуусахаас өмнө заавал харах ёстой.', 'Важливу інформацію про конкретний номер потрібно побачити до завершення роботи.'),
      ...roomToolBase, selector: '[data-training="room-instructions"]',
    },
    {
      key: 'room_photos', phase: IN_ROOM,
      title: t6('Room Photos — record room condition', 'Szobafotók — a szoba állapotának rögzítése', 'Fotos — registra el estado de la habitación', 'Ảnh phòng — ghi lại tình trạng phòng', 'Өрөөний зураг — өрөөний байдлыг бүртгэх', 'Фото номера — зафіксуйте стан номера'),
      body: t6('Use Room Photos when the hotel requires evidence of room condition or completed work. Take clear, useful photos — not unnecessary images.', 'A Szobafotókat akkor használd, ha a hotel bizonyítékot kér a szoba állapotáról vagy az elvégzett munkáról. Készíts tiszta, hasznos képeket, ne felesleges fotókat.', 'Usa Fotos cuando el hotel necesite evidencia del estado o del trabajo terminado. Haz fotos claras y útiles, no imágenes innecesarias.', 'Dùng Ảnh phòng khi khách sạn cần bằng chứng về tình trạng hoặc công việc đã hoàn tất. Chụp ảnh rõ, hữu ích, không chụp thừa.', 'Зочид буудал өрөөний байдал эсвэл дууссан ажлын нотолгоо шаардвал Өрөөний зураг ашиглана. Тод, хэрэгтэй зураг авна уу.', 'Використовуйте Фото номера, коли потрібне підтвердження стану або виконаної роботи. Робіть чіткі й корисні фото без зайвих знімків.'),
      purpose: t6('Photos provide traceable evidence when room condition needs to be verified.', 'A fotók ellenőrizhető bizonyítékot adnak, ha a szoba állapotát igazolni kell.', 'Las fotos dan evidencia verificable cuando hay que confirmar el estado.', 'Ảnh cung cấp bằng chứng có thể kiểm tra khi cần xác minh tình trạng phòng.', 'Зураг нь өрөөний байдлыг шалгах шаардлагатай үед баталгаатай нотолгоо болдог.', 'Фото дають перевірюване підтвердження, коли потрібно засвідчити стан номера.'),
      tip: t6('Only take photos that are required and appropriate for hotel operations.', 'Csak a hotel működéséhez szükséges és megfelelő fotókat készíts.', 'Haz solo las fotos necesarias y apropiadas para la operación del hotel.', 'Chỉ chụp ảnh cần thiết và phù hợp cho vận hành khách sạn.', 'Зөвхөн ажиллагаанд шаардлагатай, тохиромжтой зураг авна уу.', 'Робіть лише ті фото, які потрібні та доречні для роботи готелю.'),
      ...roomToolBase, selector: '[data-training="room-photos-button"]',
    },
    {
      key: 'dnd_photo', phase: IN_ROOM,
      title: t6('DND Photo — when the guest requests privacy', 'DND fotó — amikor a vendég nyugalmat kér', 'Foto DND — cuando el huésped pide privacidad', 'Ảnh DND — khi khách yêu cầu riêng tư', 'DND зураг — зочин хувийн орон зай хүсэх үед', 'Фото DND — коли гість просить приватності'),
      body: t6('If a Do Not Disturb sign prevents service, use DND Photo to record the situation. Do not mark DND when there is no real DND condition.', 'Ha a Ne zavarjanak jelzés miatt nem tudsz takarítani, a DND fotóval rögzítsd a helyzetet. Ne jelölj DND-t, ha nincs valódi DND helyzet.', 'Si un cartel No molestar impide el servicio, usa Foto DND para registrarlo. No marques DND si no existe realmente.', 'Nếu biển Không làm phiền ngăn việc dọn phòng, dùng Ảnh DND để ghi nhận. Không đánh dấu DND nếu thực tế không có.', 'Бүү саад бол тэмдэглэгээ үйлчилгээ хийхэд саад болж байвал DND зураг ашиглан бүртгэнэ. Бодит DND нөхцөлгүй бол DND бүү тэмдэглэ.', 'Якщо табличка Не турбувати не дозволяє обслуговування, зафіксуйте це через Фото DND. Не ставте DND, якщо такої ситуації немає.'),
      purpose: t6('A DND record explains why the room could not be serviced and protects both guest privacy and staff.', 'A DND rögzítés megmutatja, miért nem lehetett kiszolgálni a szobát, és védi a vendég magánszféráját és a dolgozót.', 'El registro DND explica por qué no se pudo atender la habitación y protege al huésped y al personal.', 'Bản ghi DND giải thích vì sao phòng chưa thể phục vụ và bảo vệ quyền riêng tư của khách cùng nhân viên.', 'DND бүртгэл өрөөг яагаад үйлчлэх боломжгүй байсныг тайлбарлаж, зочны нууцлал болон ажилтныг хамгаална.', 'Запис DND пояснює, чому номер не обслуговано, і захищає приватність гостя та персонал.'),
      ...roomToolBase, selector: '[data-training="dnd-button"]',
    },
    {
      key: 'dirty_linen', phase: IN_ROOM,
      title: t6('Dirty Linen — record what leaves the room', 'Szennyes — rögzítsd, mi kerül ki a szobából', 'Ropa sucia — registra lo que sale de la habitación', 'Đồ vải bẩn — ghi lại đồ mang ra khỏi phòng', 'Бохир цагаан хэрэглэл — өрөөнөөс гарсныг бүртгэх', 'Брудна білизна — зафіксуйте, що винесено з номера'),
      body: t6('Use Dirty Linen when linen is removed and the hotel requires quantities or item tracking. Enter only the actual linen collected from this room.', 'A Szennyes funkciót akkor használd, amikor ágyneműt vagy textíliát viszel ki, és a hotel mennyiséget vagy tételt követ. Csak a ténylegesen begyűjtött mennyiséget rögzítsd.', 'Usa Ropa sucia cuando retires ropa y el hotel controle cantidades o artículos. Registra solo lo que realmente recogiste de esta habitación.', 'Dùng Đồ vải bẩn khi mang đồ vải ra và khách sạn cần theo dõi số lượng hoặc loại. Chỉ nhập đồ thực tế thu từ phòng này.', 'Цагаан хэрэглэл гаргаж, зочид буудал тоо ширхэгийг хянадаг бол Бохир цагаан хэрэглэл ашиглана. Зөвхөн энэ өрөөнөөс бодитоор авсныг оруулна.', 'Використовуйте Брудну білизну, коли виносите текстиль і готель веде облік кількості чи типів. Вказуйте лише фактично зібране з цього номера.'),
      purpose: t6('Accurate linen data helps laundry planning, stock control and shortage prevention.', 'A pontos textiladat segíti a mosodai tervezést, készletkezelést és hiányok megelőzését.', 'Los datos correctos ayudan a lavandería, inventario y prevención de faltantes.', 'Dữ liệu đồ vải chính xác giúp lập kế hoạch giặt, kiểm soát tồn kho và tránh thiếu hụt.', 'Цагаан хэрэглэлийн зөв мэдээлэл угаалга, нөөцийн хяналт, дутагдлаас сэргийлэхэд тусална.', 'Точні дані про білизну допомагають планувати пральню, контролювати запаси й уникати нестач.'),
      ...roomToolBase, selector: '[data-training="dirty-linen-button"]',
    },
    {
      key: 'minibar', phase: IN_ROOM,
      title: t6('Minibar — record real consumption or restocking', 'Minibár — valós fogyasztás vagy feltöltés rögzítése', 'Minibar — registra consumo o reposición real', 'Minibar — ghi nhận tiêu thụ hoặc bổ sung thực tế', 'Минибар — бодит хэрэглээ эсвэл нөхөлтийг бүртгэх', 'Мінібар — зафіксуйте реальне споживання або поповнення'),
      body: t6('Use Minibar only when something was consumed, checked or restocked according to hotel procedure. Enter the real item and quantity so billing and stock remain correct.', 'A Minibárt csak akkor használd, ha a hotel eljárása szerint fogyasztást, ellenőrzést vagy feltöltést kell rögzíteni. A valós terméket és mennyiséget add meg, hogy a számlázás és készlet pontos legyen.', 'Usa Minibar solo cuando haya consumo, revisión o reposición según el procedimiento. Registra artículo y cantidad reales para mantener correctos cobro e inventario.', 'Chỉ dùng Minibar khi có tiêu thụ, kiểm tra hoặc bổ sung theo quy trình khách sạn. Nhập đúng mặt hàng và số lượng để tính phí và tồn kho chính xác.', 'Зочид буудлын журмын дагуу хэрэглээ, шалгалт эсвэл нөхөлт байвал Минибар ашиглана. Төлбөр, нөөцийг зөв байлгахын тулд бодит бараа, тоог оруулна.', 'Використовуйте Мінібар лише для фактичного споживання, перевірки чи поповнення за процедурою готелю. Вказуйте реальний товар і кількість для правильного рахунку та запасів.'),
      purpose: t6('Correct minibar entries protect guest billing and inventory accuracy.', 'A helyes minibárbejegyzés védi a vendégszámlázás és a készlet pontosságát.', 'Los registros correctos protegen la facturación del huésped y el inventario.', 'Ghi minibar đúng giúp bảo đảm hóa đơn khách và tồn kho chính xác.', 'Минибарын зөв бүртгэл зочны төлбөр болон нөөцийн нарийвчлалыг хамгаална.', 'Правильні записи мінібару забезпечують точність рахунку гостя та запасів.'),
      tip: t6('Do not add a minibar item just to practise the training.', 'Ne adj hozzá minibár tételt csak a tréning gyakorlásához.', 'No añadas un artículo solo para practicar la formación.', 'Không thêm món minibar chỉ để luyện tập hướng dẫn.', 'Зөвхөн сургалт хийхийн тулд минибарын бараа бүү нэм.', 'Не додавайте позицію мінібару лише для тренування.'),
      ...roomToolBase, selector: '[data-training="room-work-tools"]',
    },
    {
      key: 'lost_found', phase: IN_ROOM,
      title: t6('Lost & Found — log guest belongings immediately', 'Talált tárgy — azonnal rögzítsd a vendég holmiját', 'Objetos perdidos — registra pertenencias de inmediato', 'Đồ thất lạc — ghi nhận đồ của khách ngay', 'Олдсон эд зүйл — зочны эд зүйлийг нэн даруй бүртгэх', 'Забуті речі — негайно зареєструйте майно гостя'),
      body: t6('If you find a guest item, open Lost & Found and record it according to hotel procedure. Never ignore, remove or keep an item without logging it.', 'Ha vendégtárgyat találsz, nyisd meg a Talált tárgy funkciót és rögzítsd a hotel eljárása szerint. Ne hagyd figyelmen kívül, ne vidd el és ne tartsd meg rögzítés nélkül.', 'Si encuentras un objeto del huésped, abre Objetos perdidos y regístralo según el procedimiento. Nunca lo ignores, retires o guardes sin registrarlo.', 'Nếu tìm thấy đồ của khách, mở Đồ thất lạc và ghi nhận theo quy trình. Không bỏ qua, mang đi hoặc giữ lại mà không ghi nhận.', 'Зочны эд зүйл олбол Олдсон эд зүйл хэсгийг нээж журмын дагуу бүртгэнэ. Бүртгэлгүйгээр үл тоох, авч явах, хадгалах ёсгүй.', 'Якщо знайшли річ гостя, відкрийте Забуті речі та зареєструйте її за процедурою. Не ігноруйте, не виносьте й не зберігайте без реєстрації.'),
      purpose: t6('A traceable record protects the guest, staff and hotel and supports safe return of the item.', 'A követhető rögzítés védi a vendéget, a dolgozót és a hotelt, és segíti a tárgy biztonságos visszaadását.', 'Un registro trazable protege al huésped, al personal y al hotel y permite devolver el objeto con seguridad.', 'Bản ghi có thể truy vết bảo vệ khách, nhân viên và khách sạn, đồng thời giúp trả đồ an toàn.', 'Мөшгөх боломжтой бүртгэл зочин, ажилтан, зочид буудлыг хамгаалж, эд зүйлийг аюулгүй буцаахад тусална.', 'Відстежуваний запис захищає гостя, персонал і готель та допомагає безпечно повернути річ.'),
      ...roomToolBase, selector: '[data-training="lost-found-button"]',
    },
    {
      key: 'maintenance', phase: IN_ROOM,
      title: t6('Maintenance — report defects before they are missed', 'Karbantartás — jelentsd a hibát, mielőtt kimarad', 'Mantenimiento — informa fallos antes de que se pierdan', 'Bảo trì — báo lỗi trước khi bị bỏ sót', 'Засвар — гэмтлийг орхигдохоос өмнө мэдээлэх', 'Технічне обслуговування — повідомляйте про несправності вчасно'),
      body: t6('If something is broken, damaged or not working — for example AC, light, shower, lock, TV or furniture — report it through Maintenance. Add a clear description and photo when useful.', 'Ha valami törött, sérült vagy nem működik — például klíma, lámpa, zuhany, zár, TV vagy bútor — jelentsd a Karbantartás funkcióval. Adj rövid, egyértelmű leírást és szükség esetén fotót.', 'Si algo está roto, dañado o no funciona — aire, luz, ducha, cerradura, TV o muebles — repórtalo en Mantenimiento. Añade una descripción clara y foto si ayuda.', 'Nếu có thứ bị hỏng, hư hoặc không hoạt động — như điều hòa, đèn, vòi sen, khóa, TV hoặc nội thất — báo qua Bảo trì. Thêm mô tả rõ và ảnh khi hữu ích.', 'Ямар нэг зүйл эвдэрсэн, гэмтсэн эсвэл ажиллахгүй бол — AC, гэрэл, шүршүүр, цоож, TV, тавилга гэх мэт — Засвар хэсгээр мэдээлнэ. Тодорхой тайлбар, хэрэгтэй бол зураг нэмнэ.', 'Якщо щось зламане, пошкоджене або не працює — кондиціонер, світло, душ, замок, TV чи меблі — повідомте через Техобслуговування. Додайте чіткий опис і фото за потреби.'),
      purpose: t6('Early reporting lets maintenance act before the issue affects the next guest or room readiness.', 'A gyors jelentés lehetővé teszi, hogy a karbantartás a következő vendég vagy a szoba kiadhatósága előtt intézkedjen.', 'Informar pronto permite actuar antes de que el problema afecte al próximo huésped o a la disponibilidad.', 'Báo sớm giúp bảo trì xử lý trước khi ảnh hưởng khách tiếp theo hoặc khả năng sẵn sàng của phòng.', 'Эрт мэдээлснээр дараагийн зочин эсвэл өрөөний бэлэн байдалд нөлөөлөхөөс өмнө засварлах боломжтой.', 'Раннє повідомлення дозволяє усунути проблему до того, як вона вплине на наступного гостя або готовність номера.'),
      ...roomToolBase, selector: '[data-training="maintenance-button"]',
    },
    {
      key: 'notes', phase: IN_ROOM,
      title: t6('Notes — leave useful operational information', 'Megjegyzések — adj át hasznos működési információt', 'Notas — deja información operativa útil', 'Ghi chú — để lại thông tin vận hành hữu ích', 'Тэмдэглэл — хэрэгтэй ажиллагааны мэдээлэл үлдээх', 'Нотатки — залишайте корисну робочу інформацію'),
      body: t6('Use Notes for important room information that the next person or manager should know. Keep notes factual, short and clear.', 'A Megjegyzéseket olyan fontos szobainformációhoz használd, amelyet a következő kollégának vagy vezetőnek tudnia kell. Legyen tényszerű, rövid és világos.', 'Usa Notas para información importante que deba conocer la siguiente persona o el responsable. Escribe de forma objetiva, breve y clara.', 'Dùng Ghi chú cho thông tin quan trọng mà người tiếp theo hoặc quản lý cần biết. Ghi ngắn, rõ và đúng sự thật.', 'Дараагийн ажилтан эсвэл менежер мэдэх ёстой чухал өрөөний мэдээлэлд Тэмдэглэл ашиглана. Баримттай, богино, тодорхой бичнэ.', 'Використовуйте Нотатки для важливої інформації, яку має знати наступний працівник або менеджер. Пишіть фактично, коротко й чітко.'),
      purpose: t6('Clear notes prevent information from being lost between shifts and teams.', 'A világos megjegyzések megakadályozzák az információ elvesztését műszakok és csapatok között.', 'Las notas claras evitan que se pierda información entre turnos y equipos.', 'Ghi chú rõ giúp tránh mất thông tin giữa các ca và đội.', 'Тодорхой тэмдэглэл ээлж, баг хооронд мэдээлэл алдагдахаас сэргийлнэ.', 'Чіткі нотатки запобігають втраті інформації між змінами та командами.'),
      ...roomToolBase, selector: '[data-training="notes-button"]',
    },
    {
      key: 'messages', phase: IN_ROOM,
      title: t6('Messages — check communication linked to the room', 'Üzenetek — ellenőrizd a szobához tartozó kommunikációt', 'Mensajes — revisa la comunicación de la habitación', 'Tin nhắn — kiểm tra trao đổi liên quan đến phòng', 'Мессеж — өрөөтэй холбоотой харилцааг шалгах', 'Повідомлення — перевіряйте комунікацію щодо номера'),
      body: t6('Use the room communication area when you need to read or send operational information connected to this room. Keep communication relevant to the work.', 'A szobai kommunikációs részt akkor használd, ha a szobához kapcsolódó működési információt kell olvasni vagy küldeni. Maradj a munkához kapcsolódó témánál.', 'Usa el área de comunicación para leer o enviar información operativa de esta habitación. Mantén los mensajes relacionados con el trabajo.', 'Dùng khu vực trao đổi của phòng để đọc hoặc gửi thông tin vận hành liên quan. Giữ nội dung đúng mục đích công việc.', 'Энэ өрөөтэй холбоотой ажиллагааны мэдээлэл унших эсвэл илгээх шаардлагатай үед өрөөний харилцааны хэсгийг ашиглана. Ажилтай холбоотой мэдээлэл бичнэ.', 'Використовуйте комунікацію номера для читання або надсилання робочої інформації, пов’язаної з цим номером. Повідомлення мають стосуватися роботи.'),
      purpose: t6('Room-linked communication keeps context together and makes handovers easier.', 'A szobához kötött kommunikáció egy helyen tartja a kontextust és könnyíti az átadást.', 'La comunicación ligada a la habitación mantiene el contexto unido y facilita los relevos.', 'Trao đổi gắn với phòng giữ đúng ngữ cảnh và giúp bàn giao dễ hơn.', 'Өрөөтэй холбоотой харилцаа мэдээллийг нэг дор байлгаж, хүлээлцэхийг хялбар болгоно.', 'Комунікація, прив’язана до номера, зберігає контекст і полегшує передачу зміни.'),
      ...roomToolBase, selector: '[data-training="room-messages"]',
    },
    {
      key: 'complete_room', phase: FINISH,
      title: t6('Complete the room only when it is truly finished', 'Csak akkor zárd le a szobát, amikor valóban kész', 'Completa la habitación solo cuando esté realmente terminada', 'Chỉ hoàn tất phòng khi thực sự xong', 'Өрөөг үнэхээр дууссан үед л Дуусгах', 'Завершуйте номер лише коли він справді готовий'),
      body: t6('Before completing, check that cleaning is finished and every relevant item above has been handled. Then use the highlighted Complete control. This tells the operation that your work on this room is done.', 'Lezárás előtt ellenőrizd, hogy a takarítás kész és minden releváns fenti tételt kezeltél. Ezután használd a kiemelt Kész gombot. Ezzel jelzed az üzemeltetésnek, hogy a munkád a szobában befejeződött.', 'Antes de completar, confirma que la limpieza terminó y que atendiste todos los puntos relevantes. Después usa Completar. Esto informa a operaciones que tu trabajo en la habitación terminó.', 'Trước khi hoàn tất, kiểm tra dọn phòng đã xong và mọi mục liên quan đã được xử lý. Sau đó dùng nút Hoàn tất. Điều này báo cho vận hành rằng công việc phòng đã kết thúc.', 'Дуусгахаас өмнө цэвэрлэгээ бүрэн хийгдсэн, шаардлагатай бүх зүйл шийдэгдсэн эсэхийг шалгана. Дараа нь онцолсон Дуусгах удирдлагыг ашиглана. Ингэснээр ажиллагаанд таны өрөөний ажил дууссаныг мэдэгдэнэ.', 'Перед завершенням переконайтеся, що прибирання закінчено й усі потрібні пункти опрацьовано. Потім скористайтеся підсвіченим Завершити. Це повідомляє операції, що ваша робота в номері закінчена.'),
      purpose: t6('Completion changes operational room status, so it must reflect the real condition of the room.', 'A lezárás megváltoztatja az operatív szobaállapotot, ezért annak a szoba valós állapotát kell tükröznie.', 'Completar cambia el estado operativo, por lo que debe reflejar el estado real de la habitación.', 'Hoàn tất sẽ thay đổi trạng thái vận hành nên phải phản ánh đúng tình trạng thực tế của phòng.', 'Дуусгах нь ажиллагааны өрөөний төлөвийг өөрчилдөг тул бодит байдлыг илэрхийлэх ёстой.', 'Завершення змінює операційний статус номера, тому воно має відповідати реальному стану.'),
      tip: t6('If something is still unresolved, report or note it before completing the room.', 'Ha valami még nincs megoldva, jelentsd vagy jegyezd fel a szoba lezárása előtt.', 'Si queda algo sin resolver, repórtalo o anótalo antes de completar.', 'Nếu còn vấn đề chưa xử lý, hãy báo hoặc ghi chú trước khi hoàn tất phòng.', 'Шийдээгүй зүйл байвал өрөөг дуусгахаас өмнө мэдээлэх эсвэл тэмдэглэнэ.', 'Якщо щось не вирішено, повідомте або занотуйте це до завершення номера.'),
      route: '/:org', tab: 'my-tasks', selector: '[data-training="complete-room-button"]', precondition: 'has_in_progress_cleaning', waitFor: 'has_completed_assignment_today', optional: true,
    },
    {
      key: 'signout', phase: FINISH,
      title: t6('End Shift appears when your housekeeping work is finished', 'A Műszak vége akkor következik, amikor a housekeeping munka kész', 'Finaliza el turno cuando tu trabajo de housekeeping esté terminado', 'Kết thúc ca khi công việc buồng phòng đã hoàn tất', 'Housekeeping ажил дууссаны дараа ээлжээ хаах', 'Завершуйте зміну після виконання роботи housekeeping'),
      body: t6('Hotel Care will only guide you to End Shift after you have no assigned, in-progress or DND-retry rooms left for today. When your work is finished, return to Attendance and use End Shift.', 'A Hotel Care csak akkor vezet a Műszak vége funkcióhoz, ha mára nincs kijelölt, folyamatban lévő vagy DND újrapróbálkozásra váró szobád. Ha minden munka kész, térj vissza a Jelenléthez és zárd le a műszakot.', 'Hotel Care solo te llevará a Finalizar turno cuando no queden habitaciones asignadas, en curso o pendientes de reintento DND hoy. Cuando termines, vuelve a Asistencia y finaliza el turno.', 'Hotel Care chỉ hướng dẫn Kết thúc ca khi hôm nay không còn phòng được giao, đang làm hoặc chờ thử lại DND. Khi công việc xong, quay lại Chấm công và kết thúc ca.', 'Hotel Care өнөөдөр оноосон, явж буй эсвэл DND дахин оролдох өрөө үлдээгүй үед л Ээлж дуусгах руу чиглүүлнэ. Ажил дууссан бол Ирц рүү буцаж ээлжээ хаана.', 'Hotel Care покаже Завершити зміну лише коли на сьогодні не залишиться призначених, активних або DND-повторних номерів. Після завершення роботи поверніться до Відвідуваності та закрийте зміну.'),
      purpose: t6('A guarded end-of-shift prevents accidental sign-out while rooms are still waiting or in progress.', 'A védett műszakzárás megakadályozza a véletlen kijelentkezést, miközben még várakozó vagy folyamatban lévő szobák vannak.', 'Un cierre protegido evita salir accidentalmente mientras quedan habitaciones pendientes o en curso.', 'Kết thúc ca có kiểm soát tránh đăng xuất nhầm khi vẫn còn phòng chờ hoặc đang làm.', 'Хамгаалалттай ээлж хаалт нь өрөө хүлээгдэж эсвэл явж байх үед санамсаргүй гарахаас сэргийлнэ.', 'Захищене завершення зміни запобігає випадковому виходу, коли ще є очікувані або активні номери.'),
      tip: t6('If work is still pending, finish it or follow your manager’s handover process instead of signing out.', 'Ha még van munka, fejezd be vagy kövesd a vezető átadási folyamatát a kijelentkezés helyett.', 'Si queda trabajo, termínalo o sigue el proceso de entrega de tu responsable en vez de salir.', 'Nếu còn việc, hãy hoàn tất hoặc làm theo quy trình bàn giao của quản lý thay vì kết thúc ca.', 'Ажил үлдсэн бол ээлж хаахын оронд дуусгах эсвэл менежерийн хүлээлцэх журмыг дагана.', 'Якщо робота лишилася, завершіть її або дотримуйтесь процедури передачі менеджера замість виходу.'),
      route: '/:org', tab: 'attendance', selector: '[data-training="end-shift-button"]', precondition: 'has_no_pending_housekeeping_work', optional: true,
    },
  ],
};
