// Housekeeper "Your First Day" curriculum.
// Concise, interactive, mobile-first: ~9 meaningful stages instead of many
// repetitive single-button slides.
import type { I18nText, TrainingCurriculum } from '../types';

const t6 = (
  en: string,
  hu: string,
  es: string,
  vi: string,
  mn: string,
  uk: string,
): I18nText => ({ en, hu, es, vi, mn, uk });

const START_SHIFT = t6(
  '1 · Start your shift',
  '1 · Műszak kezdése',
  '1 · Empieza tu turno',
  '1 · Bắt đầu ca làm',
  '1 · Ээлжээ эхлүүлэх',
  '1 · Початок зміни',
);
const YOUR_ROOM = t6(
  '2 · Your room',
  '2 · A szobád',
  '2 · Tu habitación',
  '2 · Phòng của bạn',
  '2 · Таны өрөө',
  '2 · Ваш номер',
);
const IN_ROOM = t6(
  '3 · Working in the room',
  '3 · Munka a szobában',
  '3 · Trabajo en la habitación',
  '3 · Làm việc trong phòng',
  '3 · Өрөөнд ажиллах',
  '3 · Робота в номері',
);
const FINISH = t6(
  '4 · Finish and end of shift',
  '4 · Befejezés és műszakzárás',
  '4 · Finalizar y cerrar turno',
  '4 · Hoàn tất và kết thúc ca',
  '4 · Дуусгах ба ээлж хаах',
  '4 · Завершення та кінець зміни',
);

export const housekeeperCurriculum: TrainingCurriculum = {
  slug: 'v2_housekeeper_first_day',
  name: t6(
    'Your First Shift — Housekeeping',
    'Az első műszakod — Housekeeping',
    'Tu primer turno — Housekeeping',
    'Ca làm đầu tiên — Buồng phòng',
    'Анхны ээлж — Өрөө үйлчилгээ',
    'Ваша перша зміна — Housekeeping',
  ),
  description: t6(
    'A short, hands-on first shift: check in on site, start your real room, use the in-room tools, complete the room and close the shift correctly.',
    'Rövid, gyakorlati első műszak: helyszíni bejelentkezés, a valódi szobád elindítása, szobai eszközök használata, a szoba lezárása és a műszak helyes befejezése.',
    'Un primer turno breve y práctico: registra tu entrada en el hotel, empieza tu habitación real, usa las herramientas, completa la habitación y cierra el turno.',
    'Ca đầu tiên ngắn gọn và thực hành: chấm công tại chỗ, bắt đầu phòng thật của bạn, dùng công cụ trong phòng, hoàn tất phòng và kết thúc ca đúng cách.',
    'Богино, бодит дадлагатай анхны ээлж: газар дээр нь бүртгүүлэх, өөрийн өрөөг эхлүүлэх, өрөөний хэрэгслүүдийг ашиглах, өрөөг дуусгаж ээлжээ зөв хаах.',
    'Коротка практична перша зміна: відмітитися на місці, почати свій реальний номер, скористатися інструментами, завершити номер і правильно закрити зміну.',
  ),
  roles: ['housekeeping'],
  category: 'core',
  priority: 10,
  moduleKey: 'housekeeping',
  estMinutes: 5,
  isFullWalkthrough: true,
  steps: [
    {
      key: 'welcome',
      phase: START_SHIFT,
      title: t6(
        'Welcome — this is your working routine 👋',
        'Üdvözlünk — ez lesz a napi munkameneted 👋',
        'Bienvenido — esta será tu rutina de trabajo 👋',
        'Chào mừng — đây là quy trình làm việc của bạn 👋',
        'Тавтай морил — энэ бол таны ажлын дараалал 👋',
        'Ласкаво просимо — це ваш робочий порядок 👋',
      ),
      body: t6(
        'Hotel Care follows the same order you work in: check in, start a room, use the room tools, complete the room, then close your shift. This guide uses your real shift and your real room.',
        'A Hotel Care ugyanabban a sorrendben halad, ahogy dolgozol: bejelentkezés, szoba indítása, szobai eszközök, szoba lezárása, majd műszakzárás. Ez az útmutató a valódi műszakoddal és szobáddal dolgozik.',
        'Hotel Care sigue el mismo orden en que trabajas: entrada, iniciar habitación, herramientas, completar y cerrar turno. Esta guía usa tu turno y tu habitación reales.',
        'Hotel Care đi theo đúng thứ tự bạn làm việc: chấm công, bắt đầu phòng, dùng công cụ, hoàn tất phòng rồi kết thúc ca. Hướng dẫn dùng ca và phòng thật của bạn.',
        'Hotel Care таны ажлын дарааллаар явна: бүртгүүлэх, өрөө эхлүүлэх, хэрэгсэл ашиглах, өрөөг дуусгах, ээлжээ хаах. Энэ заавар таны бодит ээлж, бодит өрөөг ашиглана.',
        'Hotel Care йде тим самим порядком, у якому ви працюєте: вхід, початок номера, інструменти, завершення номера, закриття зміни. Навчання використовує вашу реальну зміну та номер.',
      ),
      purpose: t6(
        'One consistent routine prevents missed rooms, missing evidence and unfinished tasks.',
        'Az egységes munkamenet megelőzi a kimaradt szobákat, hiányzó bizonyítékokat és befejezetlen feladatokat.',
        'Una rutina constante evita habitaciones omitidas, evidencias faltantes y tareas sin terminar.',
        'Quy trình nhất quán giúp tránh bỏ sót phòng, thiếu bằng chứng và việc chưa xong.',
        'Тогтмол дараалал нь өрөө алгасах, нотолгоо дутуу, ажил дуусаагүй үлдэхээс сэргийлнэ.',
        'Послідовна рутина запобігає пропущеним номерам, відсутнім доказам і незавершеним завданням.',
      ),
      tip: t6(
        'Takes about 5 minutes. You can pause and continue later from the Training Center.',
        'Kb. 5 perc. Bármikor szüneteltetheted, és később folytathatod a Tréningközpontból.',
        'Dura unos 5 minutos. Puedes pausar y continuar luego desde el Centro de formación.',
        'Khoảng 5 phút. Bạn có thể tạm dừng và tiếp tục sau từ Trung tâm đào tạo.',
        'Ойролцоогоор 5 минут. Түр зогсоож, Сургалтын төвөөс дараа үргэлжлүүлж болно.',
        'Близько 5 хвилин. Можна призупинити й продовжити пізніше з Центру навчання.',
      ),
    },
    {
      key: 'signin',
      phase: START_SHIFT,
      title: t6(
        'Check in on site to start your shift',
        'Jelentkezz be a helyszínen a műszakhoz',
        'Registra tu entrada en el hotel',
        'Chấm công tại chỗ để bắt đầu ca',
        'Ээлжээ эхлүүлэхийн тулд газар дээр нь бүртгүүл',
        'Відмітьтеся на місці, щоб почати зміну',
      ),
      body: t6(
        'Use the highlighted check-in control now. If your phone asks for location, allow it — Hotel Care only uses it to confirm the shift started at the hotel. The guide continues automatically once you are checked in.',
        'Használd most a kiemelt bejelentkezés gombot. Ha a telefon helyadatot kér, engedélyezd — a Hotel Care csak a helyszíni műszakkezdés igazolására használja. Az útmutató automatikusan továbblép, ha bejelentkeztél.',
        'Usa ahora el control de entrada resaltado. Si el teléfono pide ubicación, permítela: solo confirma que el turno empezó en el hotel. La guía continuará automáticamente.',
        'Hãy dùng nút chấm công đang được làm nổi bật. Nếu điện thoại hỏi vị trí, hãy cho phép — chỉ để xác nhận ca bắt đầu tại khách sạn. Hướng dẫn sẽ tự tiếp tục.',
        'Онцолсон бүртгүүлэх товчийг одоо дарна уу. Утас байршил асуувал зөвшөөрнө үү — зөвхөн зочид буудал дээр ээлж эхэлснийг баталгаажуулна. Дараа нь заавар автоматаар үргэлжилнэ.',
        'Скористайтеся підсвіченим елементом входу. Якщо телефон запитає геолокацію — дозвольте: вона лише підтверджує початок зміни в готелі. Навчання продовжиться автоматично.',
      ),
      purpose: t6(
        'Room work and attendance must belong to the same active shift, and your hours must be correct.',
        'A szobai munka és a jelenlét ugyanahhoz az aktív műszakhoz tartozzon, és az óráid pontosak legyenek.',
        'El trabajo y la asistencia deben pertenecer al mismo turno activo y tus horas deben ser correctas.',
        'Công việc phòng và chấm công phải cùng một ca, và giờ làm phải chính xác.',
        'Өрөөний ажил ба ирц нэг ээлжид хамаарах ёстой бөгөөд таны цаг зөв байх ёстой.',
        'Робота з номерами й відвідуваність мають належати одній зміні, а ваші години — бути точними.',
      ),
      tip: t6(
        'If location was blocked before, open the location help and enable it, then try again.',
        'Ha korábban letiltottad a helyadatot, nyisd meg a helybeállítási segítséget, engedélyezd, majd próbáld újra.',
        'Si bloqueaste la ubicación antes, abre la ayuda de ubicación, actívala y vuelve a intentarlo.',
        'Nếu trước đó bạn đã chặn vị trí, mở phần trợ giúp vị trí, bật lên rồi thử lại.',
        'Өмнө нь байршлыг хориглосон бол байршлын тусламжийг нээж зөвшөөрөөд дахин оролдоно уу.',
        'Якщо раніше геолокацію заблоковано — відкрийте довідку про геолокацію, увімкніть і спробуйте знову.',
      ),
      route: '/:org',
      tab: 'attendance',
      selector: '[data-training="check-in-button"]',
      waitFor: 'is_signed_in',
    },
    {
      key: 'breaks',
      phase: START_SHIFT,
      title: t6(
        'Breaks pause your working time',
        'A szünet szünetelteti a munkaidőt',
        'Las pausas detienen tu tiempo de trabajo',
        'Giờ nghỉ tạm dừng thời gian làm việc',
        'Завсарлага ажлын цагийг түр зогсооно',
        'Перерва призупиняє робочий час',
      ),
      body: t6(
        'When you take a break, start it here and end it here. Hotel Care pauses your time automatically and resumes it when the break ends — no manual corrections needed.',
        'Ha szünetet tartasz, itt indítsd és itt zárd le. A Hotel Care automatikusan szünetelteti, majd folytatja az idődet — nem kell utólag javítani.',
        'Cuando tomes una pausa, iníciala y termínala aquí. Hotel Care detiene y reanuda tu tiempo automáticamente, sin correcciones manuales.',
        'Khi nghỉ, hãy bắt đầu và kết thúc tại đây. Hotel Care tự tạm dừng và tiếp tục tính giờ, không cần sửa tay.',
        'Завсарлага авахдаа эндээс эхлүүлж, эндээс дуусгана. Hotel Care таны цагийг автоматаар зогсоож, дараа нь үргэлжлүүлнэ.',
        'Коли йдете на перерву, починайте й завершуйте її тут. Hotel Care автоматично призупиняє та відновлює ваш час.',
      ),
      purpose: t6(
        'Correct break records keep payroll and productivity fair for you and the team.',
        'A pontos szünetrögzítés miatt a bérszámfejtés és a teljesítmény is korrekt marad.',
        'Registrar bien las pausas mantiene justos la nómina y el rendimiento.',
        'Ghi nhận giờ nghỉ đúng giúp lương và năng suất công bằng.',
        'Завсарлагыг зөв бүртгэх нь цалин, гүйцэтгэлийг шударга байлгана.',
        'Правильний облік перерв робить нарахування та показники справедливими.',
      ),
      route: '/:org',
      tab: 'attendance',
      selector: '[data-training="break-button"]',
      precondition: 'is_signed_in',
      optional: true,
    },
    {
      key: 'my_tasks',
      phase: YOUR_ROOM,
      title: t6(
        'Your rooms — start the one you are at',
        'A szobáid — indítsd azt, ahol vagy',
        'Tus habitaciones — inicia la que vas a limpiar',
        'Phòng của bạn — bắt đầu phòng bạn đang đứng',
        'Таны өрөөнүүд — очсон өрөөгөө эхлүүл',
        'Ваші номери — почніть той, у якому ви є',
      ),
      body: t6(
        'My Tasks shows only rooms assigned to you: room number, Daily or Checkout, priority and notes. Press and hold Start on the room you are about to clean. Start one room at a time — the guide continues when the room is in progress.',
        'A Saját feladatok csak a hozzád rendelt szobákat mutatja: szobaszám, Napi vagy Kijelentkezős, prioritás és megjegyzések. Tartsd lenyomva a Start gombot azon a szobán, amelyet takarítani kezdesz. Egyszerre csak egyet indíts — az útmutató folytatódik, ha a szoba folyamatban van.',
        'Mis Tareas muestra solo tus habitaciones: número, Diario o Salida, prioridad y notas. Mantén pulsado Iniciar en la habitación que vas a limpiar. Una habitación a la vez; la guía sigue cuando esté en curso.',
        'Nhiệm vụ của tôi chỉ hiện phòng của bạn: số phòng, Hằng ngày hay Trả phòng, mức ưu tiên và ghi chú. Nhấn giữ Bắt đầu ở phòng bạn sắp dọn. Mỗi lần một phòng — hướng dẫn tiếp tục khi phòng đang thực hiện.',
        'Миний даалгавар зөвхөн танд хуваарилсан өрөөг харуулна: дугаар, өдөр тутмын эсвэл гарах цэвэрлэгээ, эрэмбэ, тэмдэглэл. Цэвэрлэх өрөөнийхөө Start товчийг удаан дарна. Нэг дор нэг өрөө — өрөө эхэлмэгц заавар үргэлжилнэ.',
        '«Мої завдання» показують лише ваші номери: номер, Щоденне чи Виїзд, пріоритет і примітки. Натисніть і утримуйте «Почати» на номері, який прибиратимете. По одному номеру — навчання продовжиться, коли номер буде в роботі.',
      ),
      purpose: t6(
        'The timer, photos and tools must belong to the room you are actually cleaning.',
        'Az időmérés, a fotók és az eszközök ahhoz a szobához tartozzanak, amelyet valóban takarítasz.',
        'El tiempo, las fotos y las herramientas deben corresponder a la habitación que limpias.',
        'Thời gian, ảnh và công cụ phải thuộc đúng phòng bạn đang dọn.',
        'Цаг, зураг, хэрэгслүүд нь таны бодитоор цэвэрлэж буй өрөөнд хамаарах ёстой.',
        'Час, фото та інструменти мають належати номеру, який ви реально прибираєте.',
      ),
      tip: t6(
        'A checkout room marked as waiting should not be entered yet.',
        'A „várakozik” állapotú kijelentkezős szobába még ne menj be.',
        'No entres aún en una habitación de salida marcada como en espera.',
        'Không vào phòng trả đang ở trạng thái chờ.',
        'Хүлээгдэж буй гарах өрөөнд одоохондоо бүү ор.',
        'Не заходьте в номер після виїзду зі статусом «очікування».',
      ),
      route: '/:org',
      tab: 'housekeeping',
      selector: '[data-training="start-room-button"]',
      precondition: 'has_active_assignment',
      waitFor: 'has_in_progress_cleaning',
      optional: true,
    },
    {
      key: 'special_instructions',
      phase: IN_ROOM,
      title: t6(
        'Read the special instructions first',
        'Először olvasd el a különleges utasításokat',
        'Lee primero las instrucciones especiales',
        'Đọc hướng dẫn đặc biệt trước',
        'Эхлээд тусгай зааврыг унш',
        'Спершу прочитайте особливі вказівки',
      ),
      body: t6(
        'If this room has towel change, bed linen change, a bed configuration or manager notes, they appear here in colour before you start working. Do exactly what is written.',
        'Ha a szobában törölközőcsere, ágyneműcsere, ágyelrendezés vagy vezetői megjegyzés van, az itt jelenik meg színesen a munka előtt. Pontosan azt tedd, ami ott áll.',
        'Si la habitación requiere cambio de toallas, cambio de sábanas, configuración de camas o notas del responsable, aparecen aquí en color. Haz exactamente lo indicado.',
        'Nếu phòng cần thay khăn, thay ga giường, sắp xếp giường hoặc có ghi chú quản lý, chúng hiện ở đây bằng màu. Hãy làm đúng như hướng dẫn.',
        'Хэрэв энэ өрөөнд алчуур солих, хэвтрийн даавуу солих, орны байрлал эсвэл менежерийн тэмдэглэл байвал эндээс өнгөт харагдана. Яг бичсэнээр гүйцэтгэ.',
        'Якщо в номері потрібна заміна рушників, білизни, певна конфігурація ліжок або є примітки менеджера — вони показані тут кольором. Робіть саме так.',
      ),
      purpose: t6(
        'These instructions come from reception or your manager; missing them causes guest complaints and re-cleans.',
        'Ezek az utasítások a recepciótól vagy a vezetődtől jönnek; ha kimaradnak, vendégpanasz és újratakarítás lesz.',
        'Vienen de recepción o de tu responsable; ignorarlas provoca quejas y volver a limpiar.',
        'Các hướng dẫn này đến từ lễ tân hoặc quản lý; bỏ sót sẽ gây phàn nàn và phải dọn lại.',
        'Эдгээр заавар нь ресепшн эсвэл менежерээс ирдэг; алгасвал гомдол гарч дахин цэвэрлэх шаардлага үүснэ.',
        'Ці вказівки надходять від рецепції або менеджера; їх ігнорування спричиняє скарги та повторне прибирання.',
      ),
      route: '/:org',
      tab: 'housekeeping',
      selector: '[data-training="room-special-instructions"]',
      precondition: 'has_in_progress_cleaning',
      optional: true,
    },
    {
      key: 'room_tools',
      phase: IN_ROOM,
      title: t6(
        'Your in-room tools in one place',
        'A szobai eszközök egy helyen',
        'Tus herramientas de habitación en un solo lugar',
        'Công cụ trong phòng ở một nơi',
        'Өрөөний бүх хэрэгсэл нэг дор',
        'Усі інструменти номера в одному місці',
      ),
      body: t6(
        'This checklist holds everything you need: Room Photos (required for daily cleans), Dirty Linen, Minibar, DND, Lost & Found and Maintenance. Use each one while you are still inside the room.',
        'Ez az ellenőrzőlista tartalmaz mindent: Szobafotók (napi takarításnál kötelező), Szennyes textil, Minibár, DND, Talált tárgyak és Karbantartás. Mindegyiket még a szobában használd.',
        'Esta lista tiene todo: Fotos (obligatorias en limpieza diaria), Ropa sucia, Minibar, DND, Objetos perdidos y Mantenimiento. Úsalas mientras sigues en la habitación.',
        'Danh sách này gồm tất cả: Ảnh phòng (bắt buộc khi dọn hằng ngày), Đồ vải bẩn, Minibar, DND, Đồ thất lạc và Bảo trì. Hãy dùng khi còn ở trong phòng.',
        'Энэ жагсаалтад бүх зүйл бий: Өрөөний зураг (өдөр тутмын цэвэрлэгээнд заавал), Бохир даавуу, Минибар, DND, Олдсон эд зүйл, Засвар. Өрөөндөө байхдаа ашиглаарай.',
        'Тут зібрано все: Фото номера (обовʼязкові для щоденного прибирання), Брудна білизна, Мінібар, DND, Загублені речі та Обслуговування. Користуйтеся ними, поки ви в номері.',
      ),
      purpose: t6(
        'Recording in the room keeps evidence, stock and charges accurate — memory later is never accurate.',
        'A szobában rögzítve a bizonyíték, a készlet és a terhelés is pontos marad — utólagos emlékezet sosem pontos.',
        'Registrar en la habitación mantiene exactas las evidencias, el stock y los cargos; recordar después nunca es exacto.',
        'Ghi ngay trong phòng giúp bằng chứng, tồn kho và phí chính xác; nhớ lại sau không bao giờ chuẩn.',
        'Өрөөнд бүртгэх нь нотолгоо, нөөц, төлбөрийг үнэн зөв байлгана — дараа санах нь хэзээ ч зөв байдаггүй.',
        'Фіксація в номері зберігає точність доказів, запасів і нарахувань — памʼять потім завжди підводить.',
      ),
      tip: t6(
        'If the guest has Do Not Disturb, use DND instead of entering. If something is broken, report Maintenance with a photo.',
        'Ha a vendégnél Ne zavarj jelzés van, belépés helyett használd a DND-t. Ha valami hibás, jelentsd Karbantartásként fotóval.',
        'Si el huésped tiene No Molestar, usa DND en lugar de entrar. Si algo está roto, repórtalo en Mantenimiento con foto.',
        'Nếu khách treo Không làm phiền, dùng DND thay vì vào phòng. Nếu có hỏng hóc, báo Bảo trì kèm ảnh.',
        'Зочин DND тавьсан бол өрөөнд орохгүй DND-г ашигла. Эвдрэл байвал зурагтай Засвар мэдээл.',
        'Якщо в гостя «Не турбувати» — використайте DND замість входу. Щось зламане — створіть заявку з фото.',
      ),
      route: '/:org',
      tab: 'housekeeping',
      selector: '[data-training="room-work-tools"]',
      precondition: 'has_in_progress_cleaning',
      optional: true,
    },
    {
      key: 'messages',
      phase: IN_ROOM,
      title: t6(
        'Message your manager from the room',
        'Írj a vezetődnek a szobából',
        'Escribe a tu responsable desde la habitación',
        'Nhắn cho quản lý ngay từ phòng',
        'Өрөөнөөс менежерт мессеж бич',
        'Напишіть менеджеру просто з номера',
      ),
      body: t6(
        'Questions or blockers go here, attached to this exact room. Messages can be translated with one tap, so you can write in your own language.',
        'A kérdéseket és akadályokat ide írd — pontosan ehhez a szobához kapcsolódnak. Az üzenetek egy koppintással lefordíthatók, így a saját nyelveden írhatsz.',
        'Escribe aquí dudas o bloqueos, ligados a esta habitación. Los mensajes se traducen con un toque, así que puedes escribir en tu idioma.',
        'Câu hỏi hoặc vướng mắc ghi tại đây, gắn với đúng phòng này. Tin nhắn có thể dịch chỉ với một chạm nên bạn cứ viết bằng tiếng của mình.',
        'Асуулт, саадаа энд бичнэ — яг энэ өрөөтэй холбогдоно. Мессежийг нэг товшилтоор орчуулах тул эх хэлээрээ бичиж болно.',
        'Питання чи перешкоди пишіть тут — вони привʼязані саме до цього номера. Повідомлення перекладаються одним дотиком, тож пишіть своєю мовою.',
      ),
      purpose: t6(
        'Written, room-linked communication avoids lost verbal messages and speeds up help.',
        'Az írásos, szobához kötött kommunikáció megelőzi az elveszett szóbeli üzeneteket és gyorsítja a segítséget.',
        'La comunicación escrita y vinculada a la habitación evita mensajes verbales perdidos y acelera la ayuda.',
        'Trao đổi bằng văn bản gắn với phòng tránh mất thông tin và được hỗ trợ nhanh hơn.',
        'Өрөөтэй холбоотой бичгэн харилцаа нь мессеж алдагдахаас сэргийлж, тусламжийг хурдасгана.',
        'Письмове спілкування, привʼязане до номера, запобігає втраті усних повідомлень і пришвидшує допомогу.',
      ),
      route: '/:org',
      tab: 'housekeeping',
      selector: '[data-training="room-messages"]',
      precondition: 'has_in_progress_cleaning',
      optional: true,
    },
    {
      key: 'complete_room',
      phase: FINISH,
      title: t6(
        'Complete the room when it is guest-ready',
        'Zárd le a szobát, ha vendégkész',
        'Completa la habitación cuando esté lista',
        'Hoàn tất phòng khi sẵn sàng đón khách',
        'Зочин хүлээж авахад бэлэн болсон үед өрөөг дуусга',
        'Завершіть номер, коли він готовий до заселення',
      ),
      body: t6(
        'Press and hold Complete on the room card. Required photos and records must be done first. The guide continues automatically as soon as your first room is completed.',
        'Tartsd lenyomva a Befejezés gombot a szobakártyán. Előtte legyenek meg a kötelező fotók és rögzítések. Az útmutató automatikusan folytatódik, amint az első szobád elkészült.',
        'Mantén pulsado Completar en la tarjeta. Antes deben estar las fotos y registros obligatorios. La guía continuará en cuanto completes tu primera habitación.',
        'Nhấn giữ Hoàn tất trên thẻ phòng. Ảnh và ghi nhận bắt buộc phải xong trước. Hướng dẫn tiếp tục ngay khi bạn hoàn tất phòng đầu tiên.',
        'Өрөөний карт дээрх Дуусгах товчийг удаан дарна. Өмнө нь шаардлагатай зураг, бүртгэл хийгдсэн байх ёстой. Эхний өрөө дуусмагц заавар үргэлжилнэ.',
        'Натисніть і утримуйте «Завершити» на картці номера. Спершу мають бути обовʼязкові фото та записи. Навчання продовжиться, щойно перший номер завершено.',
      ),
      purpose: t6(
        'Completion releases the room to reception, so it must reflect reality.',
        'A lezárás felszabadítja a szobát a recepciónak, ezért a valóságot kell tükröznie.',
        'Completar libera la habitación para recepción, así que debe reflejar la realidad.',
        'Hoàn tất sẽ trả phòng cho lễ tân, nên phải đúng thực tế.',
        'Дуусгах үйлдэл өрөөг ресепшнд шилжүүлдэг тул бодит байдалтай тохирсон байх ёстой.',
        'Завершення передає номер рецепції, тож воно має відповідати дійсності.',
      ),
      tip: t6(
        'Not ready to finish now? Use “Skip this step for now” and continue the guide later.',
        'Most nem tudod befejezni? Használd az „Ezt a lépést most kihagyom” lehetőséget, és később folytasd.',
        '¿No puedes terminar ahora? Usa «Omitir este paso por ahora» y continúa después.',
        'Chưa thể hoàn tất? Chọn “Tạm bỏ qua bước này” và tiếp tục sau.',
        'Одоо дуусгах боломжгүй юу? “Энэ алхмыг одоохондоо алгасах”-ыг сонгож дараа үргэлжлүүл.',
        'Не можете завершити зараз? Скористайтесь «Пропустити цей крок зараз» і продовжіть пізніше.',
      ),
      route: '/:org',
      tab: 'housekeeping',
      selector: '[data-training="complete-room-button"]',
      precondition: 'has_in_progress_cleaning',
      waitFor: 'has_completed_assignment_today',
      optional: true,
    },
    {
      key: 'signout',
      phase: FINISH,
      title: t6(
        'End of shift — sign out on Attendance',
        'Műszak vége — jelentkezz ki a Jelenlétnél',
        'Fin del turno — cierra en Asistencia',
        'Kết thúc ca — chấm công ra ở Chấm công',
        'Ээлж дуусахад Ирц хэсгээс гарна',
        'Кінець зміни — вийдіть у «Відвідуваності»',
      ),
      body: t6(
        'When all your rooms are done, return to Attendance and sign out. Do not sign out now if you still have rooms — this step is only to show you where it is. You are ready to work. 🎉',
        'Ha minden szobáddal végeztél, térj vissza a Jelenlét oldalra és jelentkezz ki. Most ne jelentkezz ki, ha még van szobád — ez a lépés csak megmutatja, hol találod. Készen állsz a munkára. 🎉',
        'Cuando termines todas tus habitaciones, vuelve a Asistencia y cierra tu turno. No lo hagas ahora si te quedan habitaciones: este paso solo te muestra dónde está. ¡Ya estás listo! 🎉',
        'Khi xong hết phòng, quay lại Chấm công và kết thúc ca. Đừng kết thúc bây giờ nếu bạn còn phòng — bước này chỉ để chỉ chỗ. Bạn đã sẵn sàng làm việc. 🎉',
        'Бүх өрөөгөө дуусгасны дараа Ирц рүү буцаж гарна уу. Өрөө үлдсэн бол одоо бүү гар — энэ алхам зөвхөн хаана байгааг харуулж байна. Та ажилд бэлэн боллоо. 🎉',
        'Коли всі номери зроблені, поверніться у «Відвідуваність» і завершіть зміну. Не виходьте зараз, якщо ще є номери — цей крок лише показує, де це. Ви готові до роботи. 🎉',
      ),
      purpose: t6(
        'Signing out closes your working time correctly and tells the team the floor is finished.',
        'A kijelentkezés helyesen zárja a munkaidődet, és jelzi a csapatnak, hogy az emelet kész.',
        'Cerrar el turno registra bien tus horas e informa al equipo de que la planta está lista.',
        'Kết thúc ca ghi đúng giờ làm và báo cho đội biết tầng đã xong.',
        'Гарах үйлдэл ажлын цагийг зөв хааж, давхар дууссаныг багт мэдэгдэнэ.',
        'Вихід правильно закриває робочий час і повідомляє команді, що поверх завершено.',
      ),
      tip: t6(
        'Need to leave earlier? Request early sign-out so your manager can approve it.',
        'Korábban kell menned? Kérj korai kijelentkezést, hogy a vezetőd jóváhagyhassa.',
        '¿Necesitas salir antes? Solicita salida anticipada para que tu responsable la apruebe.',
        'Cần về sớm? Hãy gửi yêu cầu về sớm để quản lý duyệt.',
        'Эрт явах шаардлагатай юу? Менежер зөвшөөрөхийн тулд эрт гарах хүсэлт илгээ.',
        'Потрібно піти раніше? Надішліть запит на ранній вихід для погодження менеджером.',
      ),
      route: '/:org',
      tab: 'attendance',
      selector: '[data-training="sign-out-button"]',
      precondition: 'is_signed_in',
      optional: true,
    },
  ],
};
