// Manager — Team & Assignments module
import type { TrainingCurriculum } from '../types';

export const managerTeamCurriculum: TrainingCurriculum = {
  slug: 'v2_manager_team_and_assignments',
  name: {
    en: 'Team & Assignments',
    hu: 'Csapat és Hozzárendelések',
    es: 'Equipo y Asignaciones',
    vi: 'Đội & Phân công',
    mn: 'Баг ба Хуваарилалт',
    uk: 'Команда та Призначення',
  },
  description: {
    en: 'Team View, Auto-Assign, manual overrides and pending approvals.',
    hu: 'Csapat nézet, Auto-Hozzárendelés, kézi felülbírálás és jóváhagyások.',
    es: 'Vista del equipo, Auto-Asignar, anulación manual y aprobaciones.',
    vi: 'Xem nhóm, Tự động phân công, ghi đè thủ công, phê duyệt.',
    mn: 'Багийн харагдац, Авто-хуваарилалт, гар хуваарилалт, зөвшөөрөл.',
    uk: 'Огляд команди, авто-призначення, ручні правки та погодження.',
  },
  roles: ['manager', 'housekeeping_manager', 'admin', 'top_management_manager'],
  category: 'feature_promo',
  priority: 20,
  moduleKey: 'housekeeping',
  estMinutes: 2,
  steps: [
    {
      key: 'team_view',
      title: {
        en: 'Team View — live housekeeper cards',
        hu: 'Csapat nézet — élő szobaasszony kártyák',
        es: 'Vista del Equipo — tarjetas en vivo',
        vi: 'Xem nhóm — thẻ thời gian thực',
        mn: 'Багийн харагдац — шууд карт',
        uk: 'Огляд команди — живі картки покоївок',
      },
      body: {
        en: 'One tile per housekeeper. You see done / in progress / pending rooms, current status (working / on break / signed out) and progress against capacity — all in real time.',
        hu: 'Egy csempe szobaasszonyonként: kész / folyamatban / hátralévő szobák valós időben.',
        es: 'Una tarjeta por camarera: hechas / en curso / pendientes en tiempo real.',
        vi: 'Mỗi nhân viên một thẻ: xong / đang làm / chờ — thời gian thực.',
        mn: 'Цэвэрлэгч бүрт нэг карт: дууссан / явагдаж буй / хүлээгдэж буй.',
        uk: 'По одній картці на покоївку: виконано / у роботі / в черзі, статус і прогрес — усе в реальному часі.',
      },
      route: '/:org',
      tab: 'housekeeping',
      selector: '[data-training="team-view"]',
      precondition: 'hotel_selected',
      optional: true,
    },
    {
      key: 'pms_refresh',
      title: {
        en: 'PMS Refresh replaces daily file upload',
        hu: 'A PMS frissítés kiváltja a napi fájlfeltöltést',
        es: 'PMS Refresh reemplaza la carga diaria',
        vi: 'PMS Refresh thay cho tải file hằng ngày',
        mn: 'PMS Refresh нь өдөр тутмын файл оруулалтыг орлоно',
        uk: 'PMS Refresh замінює щоденне завантаження файлу',
      },
      body: {
        en: 'Use this button in Team View to pull today’s checkout and daily rooms from Previo. The manual PMS Upload tab is now only a fallback when an admin keeps it visible.',
        hu: 'Ezzel a gombbal a Csapat nézetben lekérhetők a mai kijelentkezési és napi szobák a Previóból.',
        es: 'Usa este botón en Vista de Equipo para traer desde Previo las salidas y habitaciones diarias de hoy.',
        vi: 'Dùng nút này trong Team View để lấy phòng checkout và phòng hằng ngày hôm nay từ Previo.',
        mn: 'Team View дээрх энэ товчоор өнөөдрийн гарах болон өдөр тутмын өрөөг Previó-оос татна.',
        uk: 'Ця кнопка в Огляді команди підтягує з Previo сьогоднішні виїзди й щоденні кімнати. Ручне завантаження PMS — лише запасний варіант.',
      },
      route: '/:org',
      tab: 'housekeeping',
      selector: '[data-training-id="pms-refresh-btn"]',
      precondition: 'hotel_selected',
      optional: true,
    },
    {
      key: 'auto_assign',
      title: {
        en: 'Auto-Assign — one-click distribution',
        hu: 'Auto-Hozzárendelés — egy kattintásos elosztás',
        es: 'Auto-Asignar — distribución de un clic',
        vi: 'Tự động phân công — một cú nhấp',
        mn: 'Автомат хуваарилалт — нэг товшилт',
        uk: 'Авто-призначення — розподіл одним кліком',
      },
      body: {
        en: 'Distributes today\'s rooms across your team based on capacity, priority tier, language match and No-Service rules. You can re-run it after edits — existing in-progress rooms are preserved.',
        hu: 'Egy kattintással szétosztja a mai szobákat kapacitás és prioritás szerint.',
        es: 'Distribuye las habitaciones de hoy según capacidad y prioridad.',
        vi: 'Phân chia phòng hôm nay theo năng lực và ưu tiên.',
        mn: 'Өнөөдрийн өрөөг чадавхи, ач холбогдлоор хуваарилна.',
        uk: 'Розподіляє сьогоднішні кімнати між командою за завантаженням, пріоритетом, мовою й правилами No-Service. Кімнати в роботі не чіпаються.',
      },
      route: '/:org',
      tab: 'housekeeping',
      selector: '[data-training="auto-assign-btn"]',
      precondition: 'hotel_selected',
      optional: true,
    },
    {
      key: 'manual_override',
      title: {
        en: 'Manual override is always available',
        hu: 'Kézi felülbírálás bármikor',
        es: 'Anulación manual siempre disponible',
        vi: 'Luôn có thể ghi đè thủ công',
        mn: 'Гар хуваарилалт үргэлж боломжтой',
        uk: 'Ручні правки завжди доступні',
      },
      body: {
        en: 'Drag any room between housekeepers, change priority, or mark No Service / DND from the room card. Auto-Assign respects your manual locks on the next run.',
        hu: 'Bármikor mozgathatsz szobát, módosíthatsz prioritást, jelölhetsz No Service-t.',
        es: 'Mueve habitaciones, cambia prioridad o marca No Service cuando quieras.',
        vi: 'Di chuyển phòng, đổi ưu tiên, đặt No Service bất cứ lúc nào.',
        mn: 'Өрөө шилжүүлэх, ач холбогдол өөрчлөх, No Service тэмдэглэх боломжтой.',
        uk: 'Перетягуйте кімнати між покоївками, змінюйте пріоритет, ставте No Service / DND. Авто-призначення шанує ваші ручні фіксації.',
      },
      route: '/:org',
      tab: 'housekeeping',
      selector: '[data-training="team-view"]',
      optional: true,
    },
    {
      key: 'yesterday_vs_today',
      title: {
        en: 'Yesterday vs Today (admins only)',
        hu: 'Tegnap vs Ma (csak adminok)',
        es: 'Ayer vs Hoy (solo admins)',
        vi: 'Hôm qua vs Hôm nay (chỉ admin)',
        mn: 'Өчигдөр vs Өнөөдөр (зөвхөн админ)',
        uk: 'Вчора vs Сьогодні (лише адміни)',
      },
      body: {
        en: 'Admins see a two-column layout: the left column is a read-only snapshot of yesterday, the right column is today\'s live rooms. Managers and other staff always see only today to keep the view simple.',
        hu: 'Az adminok két oszlopot látnak: bal oldalon a tegnapi állapot csak olvasható, jobb oldalon a mai szobák. A vezetők csak a mai nézetet látják.',
        es: 'Los admins ven dos columnas: a la izquierda un resumen de ayer (solo lectura), a la derecha las habitaciones de hoy. Los mánagers solo ven hoy.',
        vi: 'Admin xem hai cột: bên trái là hôm qua (chỉ đọc), bên phải là hôm nay. Quản lý chỉ xem hôm nay.',
        mn: 'Админ хоёр багана харна: зүүн нь өчигдрийн харагдац (зөвхөн унших), баруун нь өнөөдрийн өрөө. Менежерүүд зөвхөн өнөөдрийг харна.',
        uk: 'Адміни бачать дві колонки: ліва — вчорашній зріз (лише читання), права — сьогоднішні кімнати наживо. Менеджери бачать лише сьогодні.',
      },
      route: '/:org',
      tab: 'housekeeping',
      selector: '[data-training="team-view"]',
      optional: true,
    },
    {
      key: 'legend_expanded',
      title: {
        en: 'Legend is always in sync with the chips',
        hu: 'A jelmagyarázat mindig szinkronban van a szoba-cimkékkel',
        es: 'La leyenda siempre coincide con los chips',
        vi: 'Chú giải luôn khớp với thẻ phòng',
        mn: 'Легенд өрөөний тэмдэглэгээтэй үргэлж таарна',
        uk: 'Легенда завжди синхронізована з чіпами',
      },
      body: {
        en: 'Every colored swatch and letter badge on a room chip (T, C, RC, RTC, NS, M, C/O+1, SH, 📝) is documented in the legend. The legend now stays open by default so you never wonder what a badge means.',
        hu: 'Minden szín és betűjelzés szerepel a jelmagyarázatban, amely most alapból nyitva marad.',
        es: 'Cada color y letra en un chip aparece en la leyenda, que ahora queda abierta por defecto.',
        vi: 'Mọi màu và ký hiệu trên thẻ phòng đều có trong chú giải — luôn mở sẵn.',
        mn: 'Өрөөний тэмдэг дэх өнгө, үсэг бүр легендэд бий; легенд одоо анхнаасаа нээлттэй.',
        uk: 'Кожен колір і літерна позначка на чіпі кімнати описані в легенді, яка тепер за замовчуванням відкрита.',
      },
      route: '/:org',
      tab: 'housekeeping',
      selector: '[data-training="room-legend"]',
      optional: true,
    },
    {
      key: 'pending_approvals',
      title: {
        en: 'Pending Approvals',
        hu: 'Függő jóváhagyások',
        es: 'Aprobaciones Pendientes',
        vi: 'Chờ phê duyệt',
        mn: 'Хүлээгдэж буй зөвшөөрөл',
        uk: 'Очікують погодження',
      },
      body: {
        en: 'Early sign-out requests, time corrections and No-Service approvals land here. Approve or reject in one tap — the housekeeper sees the result instantly. Approving a cleaned room also pushes its new "clean" status back to Previo.',
        hu: 'Korai kijelentkezés és időkorrekció kérések ide érkeznek. A jóváhagyás Previóba is szinkronizálja a szobát.',
        es: 'Solicitudes de salida anticipada y correcciones aparecen aquí. Al aprobar, la habitación se marca "limpia" en Previo.',
        vi: 'Yêu cầu kết ca sớm và chỉnh giờ ở đây. Duyệt cũng gửi trạng thái sạch về Previo.',
        mn: 'Эрт гарах хүсэлт эндээс зөвшөөрнө. Зөвшөөрөх үед өрөөний "цэвэр" төлөв Previo руу автоматаар илгээнэ.',
        uk: 'Запити на ранній вихід, правки часу й No-Service тут. Погоджуйте одним дотиком — покоївка бачить результат миттєво; статус «чиста» повертається у Previo.',
      },
      route: '/:org',
      tab: 'housekeeping',
      selector: '[data-training="pending-approvals"]',
      optional: true,
    },
  ],
};
