// Manager "Run Your Day" curriculum
import type { TrainingCurriculum } from '../types';

export const managerCurriculum: TrainingCurriculum = {
  slug: 'v2_manager_run_your_day',
  name: {
    en: 'Run Your Day — Manager',
    hu: 'Vezesd a napod — Menedzser',
    es: 'Dirige tu día — Gerente',
    vi: 'Điều hành ngày của bạn',
    mn: 'Өдрөө удирдах — Менежер',
  },
  description: {
    en: 'A guided overview of every manager feature: team, assignments, tickets, attendance, invoices and revenue.',
    hu: 'Vezetett áttekintés minden vezetői funkcióról.',
    es: 'Resumen guiado de todas las funciones de gerente.',
    vi: 'Hướng dẫn tổng quan các tính năng quản lý.',
    mn: 'Менежерийн бүх функцийн заавар.',
  },
  roles: [
    'housekeeping_manager',
    'manager',
    'admin',
    'top_management',
    'top_management_manager',
  ],
  category: 'core',
  priority: 10,
  steps: [
    {
      key: 'welcome',
      title: {
        en: 'Welcome, Manager 👔',
        hu: 'Üdvözlünk, Menedzser 👔',
        es: 'Bienvenido, Gerente 👔',
        vi: 'Chào mừng Quản lý 👔',
        mn: 'Тавтай морил, Менежер 👔',
      },
      body: {
        en: 'A 3-minute tour of everything you can do here — pick a hotel, watch the team, fix bottlenecks, and approve invoices.',
        hu: 'Hárompercnyi bemutató mindenről, amit itt tehetsz.',
        es: 'Recorrido de 3 minutos por todo lo que puedes hacer.',
        vi: 'Tham quan 3 phút mọi thứ bạn có thể làm.',
        mn: '3 минутын танилцуулга — энд хийж болох бүх зүйл.',
      },
    },
    {
      key: 'hotel_switcher',
      title: {
        en: 'Pick the hotel you manage',
        hu: 'Válaszd ki a szállodát',
        es: 'Elige el hotel que gestionas',
        vi: 'Chọn khách sạn của bạn',
        mn: 'Зочид буудлаа сонгох',
      },
      body: {
        en: 'Top right. All data on every screen filters by the selected hotel. Beside it is the language switch.',
        hu: 'Jobb felül. Minden képernyő adatát szűri a kiválasztott szálloda alapján.',
        es: 'Arriba a la derecha. Filtra todos los datos por el hotel elegido.',
        vi: 'Trên cùng bên phải. Lọc dữ liệu theo khách sạn đã chọn.',
        mn: 'Баруун дээд. Сонгосон зочид буудлаар бүх дэлгэц шүүгдэнэ.',
      },
      selector: '[data-tour="hotel-switcher"]',
    },
    {
      key: 'tabs_overview',
      title: {
        en: 'Your main tabs',
        hu: 'Fő füleid',
        es: 'Tus pestañas principales',
        vi: 'Các tab chính',
        mn: 'Үндсэн табууд',
      },
      body: {
        en: 'Tickets · Rooms · Housekeeping · Attendance · Revenue · Purchase Invoices. Each one is a full module — we will tour them next.',
        hu: 'Jegyek · Szobák · Takarítás · Jelenlét · Bevétel · Beszerzési számlák.',
        es: 'Tickets · Habitaciones · Limpieza · Asistencia · Ingresos · Facturas.',
        vi: 'Vé · Phòng · Dọn phòng · Chấm công · Doanh thu · Hóa đơn mua.',
        mn: 'Тасалбар · Өрөө · Уборка · Ирц · Орлого · Худалдан авалт.',
      },
      selector: '[data-tour="main-tabs"]',
    },
    {
      key: 'team_view',
      title: {
        en: 'Team View — live housekeeper cards',
        hu: 'Csapat nézet — élő szobaasszony kártyák',
        es: 'Vista del equipo — tarjetas en vivo',
        vi: 'Xem nhóm — thẻ thời gian thực',
        mn: 'Багийн харагдац — шууд карт',
      },
      body: {
        en: 'See every housekeeper, their progress, how many rooms done / working / pending, and current status — all in real time.',
        hu: 'Lásd minden szobaasszonyt és haladását valós időben.',
        es: 'Ve a cada camarera y su progreso en tiempo real.',
        vi: 'Xem từng nhân viên và tiến độ theo thời gian thực.',
        mn: 'Цэвэрлэгч бүрийн ажлын явцыг шууд хар.',
      },
      tab: 'housekeeping',
      selector: '[data-tour="team-view"]',
    },
    {
      key: 'auto_assign',
      title: {
        en: '✨ Try Auto-Assign',
        hu: '✨ Próbáld az Auto-Hozzárendelést',
        es: '✨ Prueba Auto-Asignar',
        vi: '✨ Thử Tự động Phân công',
        mn: '✨ Автомат хуваарилалт',
      },
      body: {
        en: 'New! One click distributes today\'s rooms across your team based on capacity, priorities and No-Service rules. Tap the highlighted button to try it now — you can always override manually.',
        hu: 'Új! Egy kattintással szétosztja a mai szobákat a csapatban.',
        es: '¡Nuevo! Un clic distribuye las habitaciones de hoy.',
        vi: 'Mới! Một cú nhấp để phân chia phòng hôm nay.',
        mn: 'Шинэ! Нэг товшилтоор өнөөдрийн өрөөнүүдийг хуваарилна.',
      },
      selector: '[data-tour="auto-assign-btn"]',
    },
    {
      key: 'manual_override',
      title: {
        en: 'Manual override anytime',
        hu: 'Kézi felülbírálás bármikor',
        es: 'Anulación manual',
        vi: 'Ghi đè thủ công',
        mn: 'Гар хуваарилалт',
      },
      body: {
        en: 'You can always move rooms between housekeepers, change priority, or mark a room as No Service from the room card.',
        hu: 'Bármikor mozgathatsz szobákat és módosíthatsz prioritást.',
        es: 'Puedes mover habitaciones y cambiar prioridades en cualquier momento.',
        vi: 'Bạn có thể di chuyển phòng và đổi ưu tiên bất cứ lúc nào.',
        mn: 'Өрөөг шилжүүлэх, ач холбогдлыг өөрчлөх боломжтой.',
      },
    },
    {
      key: 'tickets',
      title: {
        en: 'Maintenance tickets',
        hu: 'Karbantartási jegyek',
        es: 'Tickets de mantenimiento',
        vi: 'Phiếu bảo trì',
        mn: 'Засварын тасалбар',
      },
      body: {
        en: 'Every maintenance issue logged — with photos, SLA timers, status and assignee. Filter by room, status or priority.',
        hu: 'Minden karbantartási probléma fotókkal és SLA-időzítőkkel.',
        es: 'Todos los problemas de mantenimiento con fotos y SLA.',
        vi: 'Mọi vấn đề bảo trì với ảnh và SLA.',
        mn: 'Бүх засварын асуудал зураг, SLA-тай.',
      },
      tab: 'tickets',
      selector: '[data-tour="tab-tickets"]',
    },
    {
      key: 'attendance',
      title: {
        en: 'Attendance & timesheets',
        hu: 'Jelenlét és munkaidő',
        es: 'Asistencia y horarios',
        vi: 'Chấm công',
        mn: 'Ирц ба цаг',
      },
      body: {
        en: 'See who is signed in right now, who is on break, and full daily timesheets for payroll.',
        hu: 'Lásd ki van bejelentkezve és a teljes napi munkaidőt.',
        es: 'Ve quién está en turno y los horarios completos.',
        vi: 'Xem ai đang làm và bảng chấm công.',
        mn: 'Хэн ажиллаж байгаа, цагийн хуваарь хар.',
      },
      tab: 'attendance',
    },
    {
      key: 'purchase_invoices',
      title: {
        en: 'Purchase Invoices',
        hu: 'Beszerzési számlák',
        es: 'Facturas de compra',
        vi: 'Hóa đơn mua hàng',
        mn: 'Худалдан авалтын нэхэмжлэх',
      },
      body: {
        en: 'Upload a PDF or photo and AI extracts vendor, amount and line items. Review, edit, then approve.',
        hu: 'Tölts fel PDF-et vagy fotót, az AI kinyeri az adatokat.',
        es: 'Sube un PDF o foto y la IA extrae los datos.',
        vi: 'Tải PDF/ảnh, AI sẽ trích xuất dữ liệu.',
        mn: 'PDF/зураг оруулахад AI мэдээллийг гаргана.',
      },
      route: '/rdhotels/purchase-invoices',
      optional: true,
    },
    {
      key: 'revenue',
      title: {
        en: 'Revenue & strategy',
        hu: 'Bevétel és stratégia',
        es: 'Ingresos y estrategia',
        vi: 'Doanh thu',
        mn: 'Орлого, стратеги',
      },
      body: {
        en: '120-day grid, pickup analytics and the AI analyst that suggests rate moves. Top managers and admins only.',
        hu: '120 napos rács, pickup elemzés és AI elemző.',
        es: 'Cuadrícula de 120 días y analista IA.',
        vi: 'Lưới 120 ngày và AI phân tích.',
        mn: '120 хоногийн хүснэгт, AI шинжээч.',
      },
      route: '/rdhotels/revenue',
      optional: true,
    },
    {
      key: 'help_menu',
      title: {
        en: 'Replay this anytime',
        hu: 'Bármikor ismételd meg',
        es: 'Repítelo cuando quieras',
        vi: 'Phát lại bất cứ lúc nào',
        mn: 'Хүссэн үедээ дахин үзэх',
      },
      body: {
        en: 'The Help icon top-right always has this tour and the others. You\'re all set!',
        hu: 'A Súgó ikon mindig elérhető a jobb felső sarokban.',
        es: 'El icono de ayuda arriba a la derecha tiene este tour siempre.',
        vi: 'Biểu tượng Trợ giúp ở góc phải trên luôn có tour này.',
        mn: 'Тусламж дүрс баруун дээд буланд хүртээмжтэй.',
      },
      selector: '[data-training="help-button"]',
    },
  ],
};
