import { createClient } from "https://esm.sh/@supabase/supabase-js@2.7.1";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const b64=(a:Uint8Array)=>{let s="";for(const b of a)s+=String.fromCharCode(b);return btoa(s)};
const unb64=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function aesKey(){const raw=Deno.env.get("GOOGLE_BUSINESS_TOKEN_KEY");if(!raw)throw new Error("GOOGLE_BUSINESS_TOKEN_KEY missing");let bytes:Uint8Array;try{bytes=unb64(raw)}catch{bytes=new TextEncoder().encode(raw)};if(bytes.length!==32)bytes=new Uint8Array(await crypto.subtle.digest("SHA-256",bytes));return crypto.subtle.importKey("raw",bytes,{name:"AES-GCM"},false,["encrypt","decrypt"])}
async function enc(v:string){const iv=crypto.getRandomValues(new Uint8Array(12));const out=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv},await aesKey(),new TextEncoder().encode(v)));return `${b64(iv)}.${b64(out)}`}
async function dec(v:string){const [a,b]=v.split(".");if(!a||!b)throw new Error("Invalid encrypted token");const out=await crypto.subtle.decrypt({name:"AES-GCM",iv:unb64(a)},await aesKey(),unb64(b));return new TextDecoder().decode(out)}
const rating=(v:unknown)=>{if(typeof v==="number")return Math.max(1,Math.min(5,Math.round(v)));const s=String(v||"").toUpperCase();return ({ONE:1,TWO:2,THREE:3,FOUR:4,FIVE:5}[s]||5)};

Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors});
 try{
  const auth=req.headers.get("Authorization");if(!auth)return json({error:"Unauthorized"},401);
  const url=Deno.env.get("SUPABASE_URL")!, anon=createClient(url,Deno.env.get("SUPABASE_ANON_KEY")!), admin=createClient(url,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
  const token=auth.replace(/^Bearer\s+/i,"");const {data:userData,error:userError}=await anon.auth.getUser(token);if(userError||!userData.user)return json({error:"Unauthorized"},401);
  const {data:profile}=await admin.from("profiles").select("role,organization_slug,is_super_admin").eq("id",userData.user.id).single();
  if(!profile||(!profile.is_super_admin&&!["admin","top_management","top_management_manager"].includes(profile.role)))return json({error:"Forbidden"},403);
  const body=await req.json().catch(()=>({}));const action=String(body.action||"status"), orgSlug=String(body.organization_slug||profile.organization_slug||"");if(!orgSlug)return json({error:"organization_slug required"},400);if(!profile.is_super_admin&&profile.organization_slug!==orgSlug)return json({error:"Forbidden"},403);
  const {data:org}=await admin.from("organizations").select("id,slug,name").eq("slug",orgSlug).maybeSingle();if(!org)return json({error:"Organization not found"},404);

  async function connection(){const {data:c}=await admin.from("google_business_connections").select("*").eq("organization_id",org.id).eq("status","active").order("updated_at",{ascending:false}).limit(1).maybeSingle();if(!c)throw new Error("Google Business Profile is not connected");return c}
  async function accessToken(){const c=await connection();if(c.access_token_ciphertext&&c.access_token_expires_at&&new Date(c.access_token_expires_at).getTime()>Date.now()+90_000)return {token:await dec(c.access_token_ciphertext),connection:c};const refresh=await dec(c.refresh_token_ciphertext);const clientId=Deno.env.get("GOOGLE_BUSINESS_CLIENT_ID"),secret=Deno.env.get("GOOGLE_BUSINESS_CLIENT_SECRET");if(!clientId||!secret)throw new Error("Google OAuth credentials are missing");const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:clientId,client_secret:secret,refresh_token:refresh,grant_type:"refresh_token"})});if(!r.ok){const t=(await r.text()).slice(0,300);await admin.from("google_business_connections").update({status:"error",last_error:`Token refresh ${r.status}: ${t}`,updated_at:new Date().toISOString()}).eq("id",c.id);throw new Error("Google authorization expired or was revoked. Reconnect Google Business Profile.")}const x=await r.json();const expiry=new Date(Date.now()+Number(x.expires_in||3600)*1000).toISOString();await admin.from("google_business_connections").update({access_token_ciphertext:await enc(String(x.access_token)),access_token_expires_at:expiry,status:"active",last_error:null,updated_at:new Date().toISOString()}).eq("id",c.id);return {token:String(x.access_token),connection:c}}
  async function gfetch(target:string,init:RequestInit={}){const {token}=await accessToken();const r=await fetch(target,{...init,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json",...(init.headers||{})}});const txt=await r.text();let data:any={};try{data=txt?JSON.parse(txt):{}}catch{data={raw:txt}}if(!r.ok){const msg=data?.error?.message||txt||`Google API ${r.status}`;throw new Error(`Google API ${r.status}: ${String(msg).slice(0,400)}`)}return data}

  if(action==="status"){
   const [{data:connections},{data:locations},{data:reviews}]=await Promise.all([
    admin.from("google_business_connections").select("id,google_account_display_name,google_account_email,status,last_sync_at,last_error,created_at").eq("organization_id",org.id),
    admin.from("google_business_locations").select("id,hotel_id,google_account_name,google_location_name,google_location_title,place_id,store_code,reply_mode,min_auto_rating,is_active,last_sync_at").eq("organization_id",org.id).order("google_location_title"),
    admin.from("google_reviews").select("id,hotel_id,google_location_id,reviewer_display_name,star_rating,comment,review_update_time,google_reply_comment,ai_language,ai_sentiment,ai_categories,ai_draft,reply_status").eq("organization_id",org.id).order("review_update_time",{ascending:false}).limit(100)
   ]);
   return json({ok:true,google_configured:Boolean(Deno.env.get("GOOGLE_BUSINESS_CLIENT_ID")&&Deno.env.get("GOOGLE_BUSINESS_CLIENT_SECRET")&&Deno.env.get("GOOGLE_BUSINESS_TOKEN_KEY")),organization:org,connections:connections||[],locations:locations||[],reviews:reviews||[]});
  }

  if(action==="start_oauth"){
   if(!Deno.env.get("GOOGLE_BUSINESS_CLIENT_ID")||!Deno.env.get("GOOGLE_BUSINESS_CLIENT_SECRET")||!Deno.env.get("GOOGLE_BUSINESS_TOKEN_KEY"))return json({error:"Google Business credentials are not configured yet"},409);
   const state=crypto.randomUUID()+crypto.randomUUID(),returnUrl=String(body.return_url||"");if(!returnUrl.startsWith("https://")&&!returnUrl.startsWith("http://localhost"))return json({error:"Invalid return_url"},400);
   await admin.from("google_business_oauth_states").delete().lt("expires_at",new Date().toISOString());const {error}=await admin.from("google_business_oauth_states").insert({state,user_id:userData.user.id,organization_id:org.id,organization_slug:orgSlug,return_url:returnUrl,expires_at:new Date(Date.now()+10*60_000).toISOString()});if(error)throw error;
   const redirectUri=`${url}/functions/v1/google-business-oauth-callback`;const p=new URLSearchParams({client_id:Deno.env.get("GOOGLE_BUSINESS_CLIENT_ID")!,redirect_uri:redirectUri,response_type:"code",scope:"https://www.googleapis.com/auth/business.manage",access_type:"offline",prompt:"consent",state,include_granted_scopes:"true"});return json({ok:true,authorization_url:`https://accounts.google.com/o/oauth2/v2/auth?${p.toString()}`});
  }

  if(action==="sync_locations"){
   const {connection:c}=await accessToken();const accounts=await gfetch("https://mybusinessaccountmanagement.googleapis.com/v1/accounts");const found:any[]=[];
   for(const a of accounts.accounts||[]){if(!a.name)continue;let pageToken="";do{const q=new URLSearchParams({readMask:"name,title,storeCode,metadata",pageSize:"100"});if(pageToken)q.set("pageToken",pageToken);const x=await gfetch(`https://mybusinessbusinessinformation.googleapis.com/v1/${a.name}/locations?${q.toString()}`);for(const l of x.locations||[]){const row={connection_id:c.id,organization_id:org.id,google_account_name:a.name,google_location_name:l.name,google_location_title:l.title||l.name,place_id:l.metadata?.placeId||null,store_code:l.storeCode||null,is_active:true,last_sync_at:new Date().toISOString(),updated_at:new Date().toISOString()};const {data:saved,error}=await admin.from("google_business_locations").upsert(row,{onConflict:"connection_id,google_location_name"}).select("id,hotel_id,google_account_name,google_location_name,google_location_title,place_id,store_code,reply_mode,min_auto_rating,is_active,last_sync_at").single();if(error)throw error;found.push(saved)}pageToken=x.nextPageToken||""}while(pageToken)}
   await admin.from("google_business_connections").update({last_sync_at:new Date().toISOString(),last_error:null,status:"active",updated_at:new Date().toISOString()}).eq("id",c.id);return json({ok:true,accounts:(accounts.accounts||[]).map((a:any)=>({name:a.name,account_name:a.accountName,type:a.type,role:a.role})),locations:found});
  }

  if(action==="map_location"){
   const id=String(body.location_id||""),hotelId=String(body.hotel_id||"");if(!id||!hotelId)return json({error:"location_id and hotel_id required"},400);const {data:h}=await admin.from("hotel_configurations").select("hotel_id,organization_id").eq("hotel_id",hotelId).eq("organization_id",org.id).maybeSingle();if(!h)return json({error:"Hotel does not belong to this organization"},400);const mode=["draft_only","auto_positive","auto_all"].includes(String(body.reply_mode))?String(body.reply_mode):"draft_only";const min=Math.max(1,Math.min(5,Number(body.min_auto_rating||4)));const {data:l,error}=await admin.from("google_business_locations").update({hotel_id:hotelId,reply_mode:mode,min_auto_rating:min,updated_at:new Date().toISOString()}).eq("id",id).eq("organization_id",org.id).select("*").maybeSingle();if(error)throw error;if(!l)return json({error:"Location not found"},404);return json({ok:true,location:l});
  }

  if(action==="sync_reviews"){
   const {data:locs}=await admin.from("google_business_locations").select("*").eq("organization_id",org.id).eq("is_active",true).not("hotel_id","is",null);let imported=0;
   for(const l of locs||[]){if(!l.google_account_name||!l.google_location_name)continue;let pageToken="";do{const q=new URLSearchParams({pageSize:"50"});if(pageToken)q.set("pageToken",pageToken);const x=await gfetch(`https://mybusiness.googleapis.com/v4/${l.google_account_name}/${l.google_location_name}/reviews?${q.toString()}`);for(const r of x.reviews||[]){const stars=rating(r.starRating);const row={organization_id:org.id,hotel_id:l.hotel_id,google_location_id:l.id,google_review_name:r.name,google_review_id:r.reviewId||String(r.name||"").split("/").pop(),reviewer_display_name:r.reviewer?.displayName||null,reviewer_profile_photo_url:r.reviewer?.profilePhotoUrl||null,star_rating:stars,comment:r.comment||null,review_create_time:r.createTime||null,review_update_time:r.updateTime||r.createTime||null,google_reply_comment:r.reviewReply?.comment||null,google_reply_update_time:r.reviewReply?.updateTime||null,reply_status:r.reviewReply?.comment?"published":"unreplied",auto_reply_eligible:stars>=Number(l.min_auto_rating||4),raw:r,updated_at:new Date().toISOString()};const {error}=await admin.from("google_reviews").upsert(row,{onConflict:"google_review_name"});if(error)throw error;imported++}pageToken=x.nextPageToken||""}while(pageToken);await admin.from("google_business_locations").update({last_sync_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",l.id)}return json({ok:true,imported});
  }

  if(action==="draft_reply"){
   const reviewId=String(body.review_id||"");if(!reviewId)return json({error:"review_id required"},400);const {data:r}=await admin.from("google_reviews").select("*,google_business_locations(google_location_title)").eq("id",reviewId).eq("organization_id",org.id).maybeSingle();if(!r)return json({error:"Review not found"},404);const key=Deno.env.get("OPENAI_API_KEY");if(!key)return json({error:"HotelCare AI is not configured"},409);const property=(r.google_business_locations as any)?.google_location_title||"the property";const prompt=`Write a professional Google Business Profile reply for ${property}. Rating: ${r.star_rating}/5. Guest review: ${r.comment||"(no written comment)"}. Reply in the same language as the guest when identifiable; otherwise English. Be warm, specific, concise (roughly 45-90 words), never invent facts, refunds or promises, do not mention AI, and do not argue. For negative reviews acknowledge the concern and invite direct contact without admitting unverified claims.`;const oa=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:Deno.env.get("OPENAI_REVIEW_MODEL")||"gpt-4.1-mini",instructions:"You write hotel and restaurant review responses for HotelCare. Output only the reply text.",input:prompt,max_output_tokens:240})});if(!oa.ok)throw new Error(`AI ${oa.status}: ${(await oa.text()).slice(0,250)}`);const ox=await oa.json();const draft=String(ox.output_text||(ox.output||[]).flatMap((o:any)=>o.content||[]).filter((c:any)=>c.type==="output_text").map((c:any)=>c.text||"").join("")).trim();if(!draft)throw new Error("AI returned an empty draft");const sentiment=r.star_rating>=4?"positive":r.star_rating===3?"mixed":"negative";await admin.from("google_reviews").update({ai_draft:draft,ai_sentiment:sentiment,ai_draft_generated_at:new Date().toISOString(),reply_status:"draft",updated_at:new Date().toISOString()}).eq("id",reviewId);return json({ok:true,draft,sentiment});
  }

  if(action==="publish_reply"){
   const reviewId=String(body.review_id||"");if(!reviewId)return json({error:"review_id required"},400);const {data:r}=await admin.from("google_reviews").select("id,google_review_name,ai_draft").eq("id",reviewId).eq("organization_id",org.id).maybeSingle();if(!r)return json({error:"Review not found"},404);const reply=String(body.reply||r.ai_draft||"").trim();if(!reply)return json({error:"Reply text is empty"},400);const x=await gfetch(`https://mybusiness.googleapis.com/v4/${r.google_review_name}/reply`,{method:"PUT",body:JSON.stringify({comment:reply})});await admin.from("google_reviews").update({google_reply_comment:reply,google_reply_update_time:x.updateTime||new Date().toISOString(),reply_status:"published",replied_at:new Date().toISOString(),replied_by:userData.user.id,updated_at:new Date().toISOString()}).eq("id",reviewId);return json({ok:true,reply:x});
  }

  return json({error:"Unsupported action"},400);
 }catch(e){console.error(e);return json({error:e instanceof Error?e.message:String(e)},500)}
});