#!/usr/bin/env python3
"""One-shot, exact-anchor patch for the existing large Auto Assign component.
Runs only on the dedicated feature branch; fails rather than guessing if main changed.
"""
from pathlib import Path

path = Path('src/components/dashboard/AutoRoomAssignmentImpl.tsx')
src = path.read_text()

def change(old: str, new: str) -> None:
    global src
    count = src.count(old)
    if count != 1:
        raise RuntimeError(f'Expected exactly one patch anchor, found {count}: {old[:100]!r}')
    src = src.replace(old, new, 1)

change("import { isPmsRtcToday } from '@/lib/pmsReadiness';", "import { moveSelectedRooms } from '@/lib/autoAssignmentBulkMove';\nimport { isPmsRtcToday } from '@/lib/pmsReadiness';")
change("  const [selectedRoomForMove, setSelectedRoomForMove] = useState<{ roomId: string; fromStaffId: string } | null>(null);", "  const [selectedRoomForMove, setSelectedRoomForMove] = useState<{ roomId: string; fromStaffId: string } | null>(null);\n  // Independently controlled: drag/tap-to-move remains available while rooms are checked for a bulk transfer.\n  const [bulkSelectedRoomIds, setBulkSelectedRoomIds] = useState<Set<string>>(new Set());\n  const [bulkDestinationStaffId, setBulkDestinationStaffId] = useState<string>('');")
change("  const automaticSectionTasks = useMemo(", "  const bulkRoomContexts = useMemo(() => assignmentPreviews.flatMap(person =>\n    person.rooms.filter(room => bulkSelectedRoomIds.has(room.id))\n      .map(room => ({ room, fromStaffId: person.staffId })),\n  ), [assignmentPreviews, bulkSelectedRoomIds]);\n\n  // Live PMS refresh and regeneration can remove rooms from the preview. Never\n  // keep a hidden selection that might later move a different room by mistake.\n  useEffect(() => {\n    const available = new Set(assignmentPreviews.flatMap(person => person.rooms.map(room => room.id)));\n    setBulkSelectedRoomIds(previous => {\n      const valid = new Set([...previous].filter(id => available.has(id)));\n      return valid.size === previous.size ? previous : valid;\n    });\n  }, [assignmentPreviews]);\n\n  const automaticSectionTasks = useMemo(")
change("  const getManagerHotel = async (): Promise<string | null> => {", "  const bulkDestination = assignmentPreviews.find(person => person.staffId === bulkDestinationStaffId);\n  const bulkMovableRooms = bulkRoomContexts.filter(entry => entry.fromStaffId !== bulkDestinationStaffId);\n  const bulkProjectedMinutes = bulkDestination\n    ? calculateTimeEstimation([...bulkDestination.rooms, ...bulkMovableRooms.map(entry => entry.room)]).totalWithBreak\n      + sectionTaskMinutesForStaff(sectionTasks, bulkDestination.staffId)\n    : null;\n\n  const toggleBulkRooms = (roomIds: string[]) => {\n    if (!roomIds.length) return;\n    setBulkSelectedRoomIds(previous => {\n      const next = new Set(previous);\n      const allSelected = roomIds.every(id => next.has(id));\n      for (const id of roomIds) {\n        if (allSelected) next.delete(id);\n        else next.add(id);\n      }\n      return next;\n    });\n  };\n\n  const getManagerHotel = async (): Promise<string | null> => {")
change("    setSelectedRoomForMove(null);\n    setShowOverAllocationDialog(false);", "    setSelectedRoomForMove(null);\n    setBulkSelectedRoomIds(new Set());\n    setBulkDestinationStaffId('');\n    setShowOverAllocationDialog(false);")
change("    setSelectedRoomForMove(null);\n    setStep('select-staff');\n  }, [open, isGozsdu, laundryDutyCommitRevision, laundryDutyIds]);", "    setSelectedRoomForMove(null);\n    setBulkSelectedRoomIds(new Set());\n    setBulkDestinationStaffId('');\n    setStep('select-staff');\n  }, [open, isGozsdu, laundryDutyCommitRevision, laundryDutyIds]);")
change("    setSelectedRoomForMove(null);\n    toast.success(t('autoAssign.undoSuccess'));", "    setSelectedRoomForMove(null);\n    setBulkSelectedRoomIds(new Set());\n    toast.success(t('autoAssign.undoSuccess'));")
change("    setSelectedRoomForMove(null);\n    void fetchData(false);", "    setSelectedRoomForMove(null);\n    setBulkSelectedRoomIds(new Set());\n    setBulkDestinationStaffId('');\n    void fetchData(false);")
change("    setFairnessMetrics(bestMetrics || computeFairnessMetrics(previews));\n    setSelectedRoomForMove(null);\n    setStep('preview');", "    setFairnessMetrics(bestMetrics || computeFairnessMetrics(previews));\n    setSelectedRoomForMove(null);\n    setBulkSelectedRoomIds(new Set());\n    setBulkDestinationStaffId('');\n    setStep('preview');")
change("    setFairnessMetrics(computeFairnessMetrics(next));\n    setSelectedRoomForMove(null);\n    setJustDroppedRoomId(roomId);", "    setFairnessMetrics(computeFairnessMetrics(next));\n    setSelectedRoomForMove(null);\n    setBulkSelectedRoomIds(previous => {\n      if (!previous.has(roomId)) return previous;\n      const nextSelection = new Set(previous);\n      nextSelection.delete(roomId);\n      return nextSelection;\n    });\n    setJustDroppedRoomId(roomId);")
change("  const removeRoomFromPreview = (roomId: string, fromStaffId: string, markExcluded: boolean = true) => {", "  const handleBulkRoomMove = () => {\n    if (!bulkDestinationStaffId || !cleaningStaffIds.has(bulkDestinationStaffId) || isLaundryner(bulkDestinationStaffId)) {\n      toast.warning('Choose an eligible housekeeper from this hotel. Laundryners cannot receive rooms.');\n      return;\n    }\n    const managerOverride = isGozsdu && hasManagerPowers(profile?.role);\n    const result = moveSelectedRooms(\n      assignmentPreviews, [...bulkSelectedRoomIds], bulkDestinationStaffId,\n      { allowGozsduManagerOverride: managerOverride, destinationIsLaundryner: isLaundryner(bulkDestinationStaffId) },\n    );\n    if (result.error) {\n      toast.warning(result.error === 'restricted_move'\n        ? 'One or more selected rooms cannot be moved under the building rules. Nothing was changed.'\n        : result.error === 'nothing_to_move'\n          ? 'All selected rooms are already with this housekeeper. Choose other rooms.'\n          : 'The selection or housekeeper has changed. Review the rooms and try again. Nothing was moved.');\n      return;\n    }\n    if (managerOverride && !gozsduAllocationRespectsBuildings(result.previews)) {\n      toast.info('Manager override: the selected rooms cross mapped buildings. Automatic allocation rules remain unchanged.');\n    }\n    pushHistory(assignmentPreviews); // one Undo restores the whole bulk action\n    setAssignmentPreviews(result.previews);\n    setFairnessMetrics(computeFairnessMetrics(result.previews));\n    if (isNextDayPlanning) {\n      setSharedByRoom(previous => {\n        const updated = new Map(previous);\n        result.movedRoomIds.forEach(id => {\n          if (updated.get(id) === bulkDestinationStaffId) updated.delete(id);\n        });\n        return updated;\n      });\n    }\n    setBulkSelectedRoomIds(new Set());\n    setBulkDestinationStaffId('');\n    setSelectedRoomForMove(null);\n    toast.success(`${result.movedRoomIds.length} rooms moved in the preview. Confirm the plan to save.`);\n  };\n\n  const removeRoomFromPreview = (roomId: string, fromStaffId: string, markExcluded: boolean = true) => {")
change("    setSelectedRoomForMove(null);\n  };\n\n  const stageMaintenanceHold =", "    setSelectedRoomForMove(null);\n    setBulkSelectedRoomIds(previous => {\n      if (!previous.has(roomId)) return previous;\n      const updated = new Set(previous);\n      updated.delete(roomId);\n      return updated;\n    });\n  };\n\n  const stageMaintenanceHold =")
change("  const renderRoomChip = (room: RoomForAssignment, preview: AssignmentPreview) => {\n    const selected = selectedRoomForMove?.roomId === room.id;", "  const renderRoomChip = (room: RoomForAssignment, preview: AssignmentPreview) => {\n    const selected = selectedRoomForMove?.roomId === room.id;\n    const checkedForBulk = bulkSelectedRoomIds.has(room.id);")
change("          selected ? 'ring-2 ring-primary ring-offset-1 scale-105' : ''\n        } ${draggingRoomId === room.id ? 'opacity-75' : ''}", "          selected ? 'ring-2 ring-primary ring-offset-1 scale-105' : checkedForBulk ? 'ring-2 ring-sky-500 ring-offset-1' : ''\n        } ${draggingRoomId === room.id ? 'opacity-75' : ''}")
change("      >\n        <span className=\"font-semibold\">{roomDisplayName(room)}</span>\n        {rtc &&", "      >\n        <button\n          type=\"button\"\n          aria-label={`${checkedForBulk ? 'Deselect' : 'Select'} room ${roomDisplayName(room)} for bulk assignment`}\n          aria-pressed={checkedForBulk}\n          title={checkedForBulk ? 'Remove from bulk selection' : 'Select for bulk assignment'}\n          onPointerDown={event => event.stopPropagation()}\n          onClick={event => { event.stopPropagation(); toggleBulkRooms([room.id]); }}\n          className={`mr-0.5 inline-flex h-5 w-5 shrink-0 items-center justify-center rounded-full border-2 bg-background/90 ${checkedForBulk ? 'border-sky-600 bg-sky-600 text-white' : 'border-current/50 text-current'} focus-visible:outline focus-visible:outline-2 focus-visible:outline-primary`}\n        >{checkedForBulk ? <Check className=\"h-3 w-3\" /> : <span className=\"h-1 w-1 rounded-full bg-current opacity-30\" />}</button>\n        <span className=\"font-semibold\">{roomDisplayName(room)}</span>\n        {rtc &&")
change("                <div className={isMobile && assignmentPreviews.length >= 3 ?", "                <div role=\"note\" className=\"flex flex-wrap items-center gap-x-2 gap-y-0.5 rounded-lg border border-sky-200 bg-sky-50/70 px-2.5 py-1.5 text-[11px] text-sky-900 dark:border-sky-900 dark:bg-sky-950/30 dark:text-sky-100\">\n                  <span><strong>One room:</strong> drag its chip or tap it, then tap another staff card.</span>\n                  <span><strong>Several rooms:</strong> tap the circles, choose a housekeeper, then tap Done.</span>\n                  <span className=\"text-muted-foreground\">Both methods work together; nothing saves until Confirm.</span>\n                </div>\n\n                <div className={isMobile && assignmentPreviews.length >= 3 ?")
change("className={`flex min-h-[130px] flex-col rounded-lg border ${isDropTarget ? 'ring-2 ring-primary' : ''}", "className={`flex min-h-[130px] flex-col rounded-lg border ${bulkDestinationStaffId === preview.staffId ? 'ring-2 ring-sky-500 bg-sky-50/30 dark:bg-sky-950/20' : ''} ${isDropTarget ? 'ring-2 ring-primary' : ''}")
change("<div className=\"flex items-center justify-between gap-1\"><span className=\"truncate text-xs font-semibold\">{preview.staffName}</span>{exceedsShift && <AlertTriangle className=\"h-3 w-3 text-destructive\" />}</div>", "<div className=\"flex items-center justify-between gap-1\"><span className=\"min-w-0 truncate text-xs font-semibold\">{preview.staffName}</span><Button type=\"button\" size=\"sm\" variant={bulkDestinationStaffId === preview.staffId ? 'default' : 'outline'} aria-pressed={bulkDestinationStaffId === preview.staffId} className=\"h-6 shrink-0 px-1 text-[9px]\" onClick={event => { event.stopPropagation(); setBulkDestinationStaffId(preview.staffId); }}>{bulkDestinationStaffId === preview.staffId ? '✓ Target' : 'Assign here'}</Button>{exceedsShift && <AlertTriangle className=\"h-3 w-3 shrink-0 text-destructive\" />}</div>")
change("<p className=\"mb-0.5 text-[9px] uppercase tracking-wide text-muted-foreground\">{t('autoAssign.checkouts')}</p>{groupByFloor(checkouts)", "<div className=\"mb-0.5 flex flex-wrap items-center justify-between gap-1\"><p className=\"text-[9px] uppercase tracking-wide text-muted-foreground\">{t('autoAssign.checkouts')}</p><button type=\"button\" className=\"text-[9px] text-sky-700 underline dark:text-sky-300\" onClick={event => { event.stopPropagation(); toggleBulkRooms(checkouts.map(room => room.id)); }}>{checkouts.every(room => bulkSelectedRoomIds.has(room.id)) ? 'Deselect all' : 'Select all'}</button></div>{groupByFloor(checkouts)")
change("<p className=\"mb-0.5 text-[9px] uppercase tracking-wide text-muted-foreground\">{t('autoAssign.daily')}</p>{groupByFloor(daily)", "<div className=\"mb-0.5 flex flex-wrap items-center justify-between gap-1\"><p className=\"text-[9px] uppercase tracking-wide text-muted-foreground\">{t('autoAssign.daily')}</p><button type=\"button\" className=\"text-[9px] text-sky-700 underline dark:text-sky-300\" onClick={event => { event.stopPropagation(); toggleBulkRooms(daily.map(room => room.id)); }}>{daily.every(room => bulkSelectedRoomIds.has(room.id)) ? 'Deselect all' : 'Select all'}</button></div>{groupByFloor(daily)")
change("                {maintenanceHoldRoomIds.size > 0 && <div className=\"rounded-lg border border-red-300 bg-red-50 px-3 py-2 text-xs text-red-800 dark:bg-red-950/30 dark:text-red-200\"><Wrench className=\"mr-1 inline h-3.5 w-3.5\" />{maintenanceHoldRoomIds.size} room{maintenanceHoldRoomIds.size === 1 ? '' : 's'} {isNextDayPlanning ? 'will be excluded from tomorrow’s plan as planned maintenance holds.' : 'will be placed on maintenance hold when you confirm.'}</div>}\n              </div>", "                {maintenanceHoldRoomIds.size > 0 && <div className=\"rounded-lg border border-red-300 bg-red-50 px-3 py-2 text-xs text-red-800 dark:bg-red-950/30 dark:text-red-200\"><Wrench className=\"mr-1 inline h-3.5 w-3.5\" />{maintenanceHoldRoomIds.size} room{maintenanceHoldRoomIds.size === 1 ? '' : 's'} {isNextDayPlanning ? 'will be excluded from tomorrow’s plan as planned maintenance holds.' : 'will be placed on maintenance hold when you confirm.'}</div>}\n              </div>")
# The bar is outside the scroll container, so it is genuinely visible while the
# manager scrolls long employee lists. The original footer remains untouched.
change("          <DialogFooter className={isGozsdu ?", "          {step === 'preview' && bulkRoomContexts.length > 0 && (\n            <div data-testid=\"auto-assign-bulk-bar\" className=\"flex shrink-0 flex-wrap items-center gap-2 rounded-lg border-2 border-sky-300 bg-background p-2 shadow-sm\">\n              <span className=\"text-xs font-semibold\">{bulkRoomContexts.length} selected · {bulkRoomContexts.filter(entry => entry.room.is_checkout_room || entry.room.pms_metadata?.scheduledDepartureToday === true).length} checkout · {bulkRoomContexts.filter(entry => !isCheckoutLike(entry.room)).length} daily</span>\n              <Select value={bulkDestinationStaffId || undefined} onValueChange={setBulkDestinationStaffId}>\n                <SelectTrigger className=\"h-8 min-w-[145px] flex-1 text-xs sm:max-w-[230px]\" aria-label=\"Bulk assignment destination housekeeper\"><SelectValue placeholder=\"Choose housekeeper\" /></SelectTrigger>\n                <SelectContent>{assignmentPreviews.filter(person => cleaningStaffIds.has(person.staffId) && !isLaundryner(person.staffId)).map(person => <SelectItem key={person.staffId} value={person.staffId}>{person.staffName}</SelectItem>)}</SelectContent>\n              </Select>\n              {bulkProjectedMinutes !== null && <span className={`text-[11px] ${bulkProjectedMinutes > STANDARD_SHIFT_MINUTES ? 'font-semibold text-destructive' : 'text-muted-foreground'}`}>After move: {formatMinutesToTime(bulkProjectedMinutes)}{bulkProjectedMinutes > STANDARD_SHIFT_MINUTES ? ' · exceeds shift' : ''}</span>}\n              <Button type=\"button\" size=\"sm\" className=\"h-8 flex-1 sm:flex-none\" disabled={!bulkDestinationStaffId || bulkMovableRooms.length === 0 || !cleaningStaffIds.has(bulkDestinationStaffId) || isLaundryner(bulkDestinationStaffId)} onClick={handleBulkRoomMove}>Done · Move {bulkMovableRooms.length} room{bulkMovableRooms.length === 1 ? '' : 's'}</Button>\n              <Button type=\"button\" size=\"sm\" variant=\"ghost\" className=\"h-8 text-xs\" onClick={() => setBulkSelectedRoomIds(new Set())}>Clear selection</Button>\n              <span className=\"w-full text-[10px] text-muted-foreground\">This changes the preview only. Use Proceed to Confirm to save.</span>\n            </div>\n          )}\n\n          <DialogFooter className={isGozsdu ?")
# No new DB writes, migrations, or changes to the existing drag/drop handler.
path.write_text(src)
print('Applied guarded parallel drag + multi-select UI patch successfully')
