-- Reduce redundant database I/O generated by the frequent Previo revenue sync.
--
-- The sync intentionally remains frequent and authoritative; these guards only
-- suppress writes that carry no new business information and make pickup reads
-- use the small non-zero movement subset.

CREATE INDEX IF NOT EXISTS idx_pickup_snapshots_nonzero_hotel_time
ON public.pickup_snapshots (hotel_id, captured_at DESC, stay_date)
INCLUDE (delta)
WHERE delta <> 0;

CREATE OR REPLACE FUNCTION public.skip_redundant_revenue_daily_snapshot()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $$
DECLARE
  v_prev public.revenue_daily_snapshots%ROWTYPE;
BEGIN
  SELECT s.*
    INTO v_prev
  FROM public.revenue_daily_snapshots s
  WHERE s.hotel_id = NEW.hotel_id
    AND s.stay_date = NEW.stay_date
  ORDER BY s.captured_at DESC
  LIMIT 1;

  -- Preserve a daily checkpoint, but do not write another row when the state
  -- is identical to the latest snapshot from the same Budapest business day.
  IF FOUND
     AND v_prev.captured_date IS NOT DISTINCT FROM NEW.captured_date
     AND v_prev.rooms_sold IS NOT DISTINCT FROM NEW.rooms_sold
     AND v_prev.rooms_available IS NOT DISTINCT FROM NEW.rooms_available
     AND v_prev.occupancy_pct IS NOT DISTINCT FROM NEW.occupancy_pct
     AND v_prev.revenue_eur IS NOT DISTINCT FROM NEW.revenue_eur
     AND v_prev.adr_eur IS NOT DISTINCT FROM NEW.adr_eur
     AND v_prev.new_bookings IS NOT DISTINCT FROM NEW.new_bookings
  THEN
    RETURN NULL;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_skip_redundant_revenue_daily_snapshot
ON public.revenue_daily_snapshots;
CREATE TRIGGER trg_skip_redundant_revenue_daily_snapshot
BEFORE INSERT ON public.revenue_daily_snapshots
FOR EACH ROW
EXECUTE FUNCTION public.skip_redundant_revenue_daily_snapshot();

CREATE OR REPLACE FUNCTION public.skip_zero_previo_pickup_snapshot()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $$
BEGIN
  -- previo_sync_diff rows are movement events. A zero delta contains no event
  -- and is not consumed by the movement/published-payload queries.
  IF NEW.source = 'previo_sync_diff' AND COALESCE(NEW.delta, 0) = 0 THEN
    RETURN NULL;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_skip_zero_previo_pickup_snapshot
ON public.pickup_snapshots;
CREATE TRIGGER trg_skip_zero_previo_pickup_snapshot
BEFORE INSERT ON public.pickup_snapshots
FOR EACH ROW
EXECUTE FUNCTION public.skip_zero_previo_pickup_snapshot();

CREATE OR REPLACE FUNCTION public.skip_noop_revenue_rate_update()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $$
BEGIN
  -- Previo sends a fresh captured_at on every poll. If every business value is
  -- unchanged, keep the existing tuple instead of rewriting it plus its indexes
  -- and WAL merely to advance timestamps.
  IF OLD.hotel_id IS NOT DISTINCT FROM NEW.hotel_id
     AND OLD.organization_slug IS NOT DISTINCT FROM NEW.organization_slug
     AND OLD.stay_date IS NOT DISTINCT FROM NEW.stay_date
     AND OLD.obk_id IS NOT DISTINCT FROM NEW.obk_id
     AND OLD.room_type_name IS NOT DISTINCT FROM NEW.room_type_name
     AND OLD.rate_plan_id IS NOT DISTINCT FROM NEW.rate_plan_id
     AND OLD.occupancy IS NOT DISTINCT FROM NEW.occupancy
     AND OLD.price IS NOT DISTINCT FROM NEW.price
     AND OLD.currency IS NOT DISTINCT FROM NEW.currency
     AND OLD.min_stay IS NOT DISTINCT FROM NEW.min_stay
     AND OLD.closed_to_arrival IS NOT DISTINCT FROM NEW.closed_to_arrival
     AND OLD.closed_to_departure IS NOT DISTINCT FROM NEW.closed_to_departure
     AND OLD.source IS NOT DISTINCT FROM NEW.source
  THEN
    RETURN NULL;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_skip_noop_revenue_rate_update
ON public.revenue_room_type_rates;
CREATE TRIGGER trg_skip_noop_revenue_rate_update
BEFORE UPDATE ON public.revenue_room_type_rates
FOR EACH ROW
EXECUTE FUNCTION public.skip_noop_revenue_rate_update();

-- Exact duplicate of idx_revenue_booking_nights_created. Maintaining both
-- doubled index work during every booking-night refresh.
DROP INDEX IF EXISTS public.revenue_booking_nights_created_idx;
